/**
 * Committed hit-zone catalog — ship defaults for every player.
 *
 * Admin «Lagre» only writes browser localStorage. Use Admin → Treffområde →
 * «Skriv til repo (dev)» to overwrite this file from calibrated overrides,
 * then commit + push so GitHub has the real defaults.
 *
 * Zones:
 * - Yellow (head): instant kill — headshot
 * - Orange (neck): lucky instant kill — not an aim point
 * - Green (chest): instant kill — bird drops
 * - Red: vital — short ettersøk
 * - Body ellipse: wound — ettersøk toward max fly radius
 * - Outside: clean miss
 *
 * Auto-generated 2026-07-30T18:25:21.145Z — do not hand-edit unless needed.
 */

import type { BirdSpriteId } from "@/lib/hunt/birdSprites";

export type BirdHitZone = {
  vitalCxPx: number;
  vitalCyPx: number;
  instantDiameterMm: number;
  vitalDiameterMm: number;
  headCxPx: number;
  headCyPx: number;
  headDiameterMm: number;
  /** Neck rectangle centre (native topp px) — lucky instant kill. */
  neckCxPx: number;
  neckCyPx: number;
  neckWidthMm: number;
  neckHeightMm: number;
  neckRotationDeg: number;
  bodyRxMm: number;
  bodyRyMm: number;
  bodyOffsetXMm: number;
  bodyOffsetYMm: number;
  bodyRotationDeg: number;
};

export const BIRD_HIT_ZONE_CATALOG: Record<BirdSpriteId, BirdHitZone> = {
  "tiur-1": {
    vitalCxPx: 39.2,
    vitalCyPx: 75,
    instantDiameterMm: 61,
    vitalDiameterMm: 106,
    headCxPx: 29.7,
    headCyPx: 28.7,
    headDiameterMm: 52,
    neckCxPx: 35.3,
    neckCyPx: 47.8,
    neckWidthMm: 28,
    neckHeightMm: 123,
    neckRotationDeg: 349,
    bodyRxMm: 72,
    bodyRyMm: 96,
    bodyOffsetXMm: 11,
    bodyOffsetYMm: 23,
    bodyRotationDeg: 339,
  },
  "tiur-2": {
    vitalCxPx: 53.6,
    vitalCyPx: 47.9,
    instantDiameterMm: 67,
    vitalDiameterMm: 105,
    headCxPx: 59.4,
    headCyPx: 16.6,
    headDiameterMm: 42,
    neckCxPx: 57.2,
    neckCyPx: 29.6,
    neckWidthMm: 28,
    neckHeightMm: 126,
    neckRotationDeg: 7,
    bodyRxMm: 69,
    bodyRyMm: 131,
    bodyOffsetXMm: -47,
    bodyOffsetYMm: 36,
    bodyRotationDeg: 59,
  },
  "tiur-1b": {
    vitalCxPx: 100,
    vitalCyPx: 162,
    instantDiameterMm: 66,
    vitalDiameterMm: 95,
    headCxPx: 86.6,
    headCyPx: 63.4,
    headDiameterMm: 48,
    neckCxPx: 98.8,
    neckCyPx: 103,
    neckWidthMm: 28,
    neckHeightMm: 110,
    neckRotationDeg: 352,
    bodyRxMm: 74,
    bodyRyMm: 105,
    bodyOffsetXMm: -24,
    bodyOffsetYMm: 39,
    bodyRotationDeg: 38,
  },
  "tiur-2b": {
    vitalCxPx: 188.4,
    vitalCyPx: 170.8,
    instantDiameterMm: 82,
    vitalDiameterMm: 102,
    headCxPx: 200.4,
    headCyPx: 46.5,
    headDiameterMm: 42,
    neckCxPx: 203.4,
    neckCyPx: 102.4,
    neckWidthMm: 16,
    neckHeightMm: 114,
    neckRotationDeg: 3,
    bodyRxMm: 48,
    bodyRyMm: 85,
    bodyOffsetXMm: -18,
    bodyOffsetYMm: 17,
    bodyRotationDeg: 35,
  },
  "tiur-3b": {
    vitalCxPx: 65,
    vitalCyPx: 96.5,
    instantDiameterMm: 80,
    vitalDiameterMm: 113,
    headCxPx: 75,
    headCyPx: 40.6,
    headDiameterMm: 42,
    neckCxPx: 68.1,
    neckCyPx: 60.2,
    neckWidthMm: 28,
    neckHeightMm: 83,
    neckRotationDeg: 7,
    bodyRxMm: 69,
    bodyRyMm: 91,
    bodyOffsetXMm: -8,
    bodyOffsetYMm: 16,
    bodyRotationDeg: 25,
  },
  "tiur-4b": {
    vitalCxPx: 110,
    vitalCyPx: 91,
    instantDiameterMm: 66,
    vitalDiameterMm: 100,
    headCxPx: 130.5,
    headCyPx: 42.7,
    headDiameterMm: 42,
    neckCxPx: 122.2,
    neckCyPx: 62.4,
    neckWidthMm: 24,
    neckHeightMm: 82,
    neckRotationDeg: 21,
    bodyRxMm: 56,
    bodyRyMm: 123,
    bodyOffsetXMm: -27,
    bodyOffsetYMm: 23,
    bodyRotationDeg: 52,
  },
  "tiur-n1": {
    vitalCxPx: 479.7,
    vitalCyPx: 172.5,
    instantDiameterMm: 132,
    vitalDiameterMm: 161,
    headCxPx: 596.5,
    headCyPx: 56.7,
    headDiameterMm: 67,
    neckCxPx: 553.1,
    neckCyPx: 91.9,
    neckWidthMm: 43,
    neckHeightMm: 81,
    neckRotationDeg: 54,
    bodyRxMm: 191,
    bodyRyMm: 117,
    bodyOffsetXMm: -62,
    bodyOffsetYMm: 42,
    bodyRotationDeg: 336,
  },
  "tiur-n1-alert": {
    vitalCxPx: 392,
    vitalCyPx: 424.8,
    instantDiameterMm: 95,
    vitalDiameterMm: 124,
    headCxPx: 421.6,
    headCyPx: 69.2,
    headDiameterMm: 48,
    neckCxPx: 440.2,
    neckCyPx: 217.3,
    neckWidthMm: 25,
    neckHeightMm: 160,
    neckRotationDeg: 3,
    bodyRxMm: 80,
    bodyRyMm: 114,
    bodyOffsetXMm: -10,
    bodyOffsetYMm: 27,
    bodyRotationDeg: 40,
  },
  "orre-1": {
    vitalCxPx: 27.2,
    vitalCyPx: 41.8,
    instantDiameterMm: 77,
    vitalDiameterMm: 121,
    headCxPx: 22,
    headCyPx: 20.4,
    headDiameterMm: 42,
    neckCxPx: 22.2,
    neckCyPx: 27.7,
    neckWidthMm: 32,
    neckHeightMm: 54,
    neckRotationDeg: 351,
    bodyRxMm: 86,
    bodyRyMm: 135,
    bodyOffsetXMm: 26,
    bodyOffsetYMm: 42,
    bodyRotationDeg: 318,
  },
  "orre-2": {
    vitalCxPx: 74.8,
    vitalCyPx: 73.7,
    instantDiameterMm: 66,
    vitalDiameterMm: 93,
    headCxPx: 81.4,
    headCyPx: 30.1,
    headDiameterMm: 42,
    neckCxPx: 79.7,
    neckCyPx: 48.7,
    neckWidthMm: 20,
    neckHeightMm: 89,
    neckRotationDeg: 0,
    bodyRxMm: 67,
    bodyRyMm: 121,
    bodyOffsetXMm: -36,
    bodyOffsetYMm: 43,
    bodyRotationDeg: 41,
  },
  "orre-1b": {
    vitalCxPx: 81.5,
    vitalCyPx: 107.5,
    instantDiameterMm: 76,
    vitalDiameterMm: 108,
    headCxPx: 64.5,
    headCyPx: 39.4,
    headDiameterMm: 42,
    neckCxPx: 72.2,
    neckCyPx: 66.5,
    neckWidthMm: 19,
    neckHeightMm: 79,
    neckRotationDeg: 353,
    bodyRxMm: 63,
    bodyRyMm: 94,
    bodyOffsetXMm: 3,
    bodyOffsetYMm: 21,
    bodyRotationDeg: 349,
  },
  "orre-2b": {
    vitalCxPx: 117.5,
    vitalCyPx: 85,
    instantDiameterMm: 86,
    vitalDiameterMm: 121,
    headCxPx: 130.5,
    headCyPx: 28.8,
    headDiameterMm: 42,
    neckCxPx: 128.8,
    neckCyPx: 50.9,
    neckWidthMm: 20,
    neckHeightMm: 75,
    neckRotationDeg: 6,
    bodyRxMm: 68,
    bodyRyMm: 107,
    bodyOffsetXMm: -11,
    bodyOffsetYMm: 24,
    bodyRotationDeg: 32,
  },
  "orre-3b": {
    vitalCxPx: 113,
    vitalCyPx: 100.5,
    instantDiameterMm: 73,
    vitalDiameterMm: 107,
    headCxPx: 130.2,
    headCyPx: 36,
    headDiameterMm: 42,
    neckCxPx: 122.8,
    neckCyPx: 60.5,
    neckWidthMm: 19,
    neckHeightMm: 81,
    neckRotationDeg: 11,
    bodyRxMm: 62,
    bodyRyMm: 110,
    bodyOffsetXMm: -36,
    bodyOffsetYMm: 26,
    bodyRotationDeg: 47,
  },
  "orre-4b": {
    vitalCxPx: 119.5,
    vitalCyPx: 74.5,
    instantDiameterMm: 98,
    vitalDiameterMm: 142,
    headCxPx: 158,
    headCyPx: 30.4,
    headDiameterMm: 42,
    neckCxPx: 145,
    neckCyPx: 48,
    neckWidthMm: 34,
    neckHeightMm: 108,
    neckRotationDeg: 41,
    bodyRxMm: 130,
    bodyRyMm: 82,
    bodyOffsetXMm: -13,
    bodyOffsetYMm: 11,
    bodyRotationDeg: 350,
  },
  "orre-5b": {
    vitalCxPx: 82.5,
    vitalCyPx: 134.5,
    instantDiameterMm: 72,
    vitalDiameterMm: 105,
    headCxPx: 83.6,
    headCyPx: 32.9,
    headDiameterMm: 36,
    neckCxPx: 82.8,
    neckCyPx: 73.4,
    neckWidthMm: 15,
    neckHeightMm: 94,
    neckRotationDeg: 0,
    bodyRxMm: 60,
    bodyRyMm: 97,
    bodyOffsetXMm: 3,
    bodyOffsetYMm: 24,
    bodyRotationDeg: 353,
  },
  "orre-n1": {
    vitalCxPx: 413.3,
    vitalCyPx: 555,
    instantDiameterMm: 66,
    vitalDiameterMm: 90,
    headCxPx: 594.7,
    headCyPx: 631,
    headDiameterMm: 30,
    neckCxPx: 524.7,
    neckCyPx: 575.7,
    neckWidthMm: 20,
    neckHeightMm: 50,
    neckRotationDeg: 120,
    bodyRxMm: 70,
    bodyRyMm: 42,
    bodyOffsetXMm: -15,
    bodyOffsetYMm: -8,
    bodyRotationDeg: 22,
  },
  "orre-n1-alert": {
    vitalCxPx: 383.4,
    vitalCyPx: 359.5,
    instantDiameterMm: 86,
    vitalDiameterMm: 105,
    headCxPx: 453.8,
    headCyPx: 56.9,
    headDiameterMm: 42,
    neckCxPx: 429.2,
    neckCyPx: 206.4,
    neckWidthMm: 26,
    neckHeightMm: 140,
    neckRotationDeg: 5,
    bodyRxMm: 54,
    bodyRyMm: 90,
    bodyOffsetXMm: -10,
    bodyOffsetYMm: 11,
    bodyRotationDeg: 39,
  },
  "ugle-1": {
    vitalCxPx: 62.7,
    vitalCyPx: 82,
    instantDiameterMm: 116,
    vitalDiameterMm: 146,
    headCxPx: 62.3,
    headCyPx: 30.4,
    headDiameterMm: 42,
    neckCxPx: 61.3,
    neckCyPx: 45.2,
    neckWidthMm: 40,
    neckHeightMm: 62,
    neckRotationDeg: 0,
    bodyRxMm: 83,
    bodyRyMm: 123,
    bodyOffsetXMm: 0,
    bodyOffsetYMm: 32,
    bodyRotationDeg: 0,
  },
};
