/**
 * Realistic bird perch points per spot landscape image.
 *
 * ## Placement guides (`/public/images/spot/placement/`)
 * Mark birds on a copy of the spot photo. The agent reads:
 * - **Position** — center of each marker (% of frame)
 * - **Shape** — square = tiur, circle = orrhane
 * - **Color** — distance band (and thus sprite size):
 *     Rød    110–170 m  — synlig med bare øyne
 *     Lilla  180–230 m  — synlig med bare øyne
 *     Grønn  240–300 m  — krever kikkert/termisk
 *     Gul    300–500 m  — krever kikkert/termisk
 *
 * Coordinates are **percent of the image frame** (same as BirdVisualPlacement):
 * - x: 0 = left edge, 100 = right
 * - y: 0 = top, 100 = bottom
 * - Point ≈ center of the bird body on the perch.
 *
 * Spot images without a placement guide get **no** birds (empty catalog).
 */

import type { BirdSpecies } from "@/lib/hunt/birds";

export type SpotPerch = {
  /** 0–100, left → right */
  x: number;
  /** 0–100, top → bottom */
  y: number;
  /** From marker shape (square → tiur, circle → orrhane). */
  species: BirdSpecies;
  /** Inclusive distance band from marker color. */
  distanceMinM: number;
  distanceMaxM: number;
  /** Optional human note (which tree / color). */
  note?: string;
};

export type SpotPerchCatalog = Record<string, SpotPerch[]>;

export const SPOT_PERCHES: SpotPerchCatalog = {
  "/images/spot/spot1.png": [
    {
      x: 18.3,
      y: 48.2,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 19.4,
      y: 44.4,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 24.4,
      y: 47.4,
      species: "orrhane",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul sirkel",
    },
    {
      x: 26.2,
      y: 43.7,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 28.2,
      y: 48.3,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 37.1,
      y: 46.3,
      species: "tiur",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla firkant",
    },
    {
      x: 38.2,
      y: 51.2,
      species: "tiur",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla firkant",
    },
    {
      x: 46.3,
      y: 48.2,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
    {
      x: 60.3,
      y: 36.6,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 64.3,
      y: 48.2,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
  ],
  "/images/spot/spot2.png": [
    {
      x: 9.7,
      y: 38.1,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 29.7,
      y: 47.6,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
    {
      x: 30.4,
      y: 29.5,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 31.1,
      y: 39.1,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 43.4,
      y: 36.2,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 43.8,
      y: 40.0,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 50.0,
      y: 50.0,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 61.8,
      y: 40.0,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 69.7,
      y: 40.0,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
  ],
  "/images/spot/spot4.png": [
    {
      x: 17.2,
      y: 44.0,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 26.1,
      y: 45.1,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 29.3,
      y: 36.2,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 36.9,
      y: 49.8,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 42.9,
      y: 49.8,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 45.7,
      y: 45.2,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 48.4,
      y: 51.7,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 56.3,
      y: 46.2,
      species: "tiur",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla firkant",
    },
    {
      x: 63.1,
      y: 47.2,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 66.9,
      y: 47.2,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 71.3,
      y: 43.9,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
    {
      x: 83.4,
      y: 51.7,
      species: "orrhane",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul sirkel",
    },
  ],
  "/images/spot/spot5.png": [
    {
      x: 14.4,
      y: 39.3,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 15.7,
      y: 36.1,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 16.5,
      y: 44.1,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 21.8,
      y: 43.7,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 26.7,
      y: 60.7,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 42.3,
      y: 60.7,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 64.4,
      y: 55.2,
      species: "orrhane",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul sirkel",
    },
    {
      x: 71.7,
      y: 50.9,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 75.3,
      y: 47.0,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
    {
      x: 76.6,
      y: 43.7,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
  ],
  "/images/spot/spot6.jpg": [
    {
      x: 21.7,
      y: 55.8,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 27.1,
      y: 36.4,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 29.8,
      y: 43.1,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 43.0,
      y: 51.6,
      species: "tiur",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla firkant",
    },
    {
      x: 56.7,
      y: 50.7,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 66.9,
      y: 50.0,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 73.6,
      y: 43.9,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
  ],
  "/images/spot/spot7.jpg": [
    {
      x: 20.3,
      y: 61.5,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 27.3,
      y: 64.4,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 33.7,
      y: 56.0,
      species: "tiur",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla firkant",
    },
    {
      x: 40.4,
      y: 58.3,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 40.4,
      y: 74.7,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 42.5,
      y: 47.2,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 44.2,
      y: 56.0,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 45.0,
      y: 72.8,
      species: "orrhane",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul sirkel",
    },
    {
      x: 46.6,
      y: 75.5,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 51.6,
      y: 55.6,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 56.9,
      y: 68.3,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 58.4,
      y: 47.2,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 79.3,
      y: 30.4,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 80.8,
      y: 43.5,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
  ],
  "/images/spot/spot8.jpg": [
    {
      x: 23.6,
      y: 48.4,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 32.2,
      y: 21.6,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 38.8,
      y: 51.3,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 43.2,
      y: 36.4,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 52.0,
      y: 53.1,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 52.3,
      y: 48.4,
      species: "tiur",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla firkant",
    },
    {
      x: 54.8,
      y: 46.3,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 57.8,
      y: 48.4,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 61.1,
      y: 46.3,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
  ],
  "/images/spot/spot9.png": [
    {
      x: 12.7,
      y: 54.2,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 20.2,
      y: 36.3,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 23.1,
      y: 55.1,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 41.9,
      y: 48.3,
      species: "tiur",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla firkant",
    },
    {
      x: 49.3,
      y: 53.8,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 57.7,
      y: 45.8,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 69.7,
      y: 57.1,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 74.6,
      y: 55.1,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
  ],
  "/images/spot/spot10.png": [
    {
      x: 24.0,
      y: 40.0,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 37.0,
      y: 53.1,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 56.6,
      y: 52.0,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
  ],
  "/images/spot/spot11.png": [
    {
      x: 21.8,
      y: 53.0,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
    {
      x: 31.0,
      y: 55.4,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 43.5,
      y: 59.2,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 57.0,
      y: 52.3,
      species: "tiur",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla firkant",
    },
    {
      x: 59.4,
      y: 59.2,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 72.9,
      y: 55.4,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
    {
      x: 76.0,
      y: 42.2,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
  ],
  "/images/spot/spot12.png": [
    {
      x: 25.7,
      y: 59.6,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
    {
      x: 27.9,
      y: 59.2,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 40.1,
      y: 59.6,
      species: "tiur",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla firkant",
    },
    {
      x: 43.8,
      y: 65.5,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 51.9,
      y: 49.0,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 54.3,
      y: 61.6,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 56.2,
      y: 63.5,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 57.5,
      y: 61.6,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
    {
      x: 71.0,
      y: 63.5,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 76.5,
      y: 53.9,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
  ],
  "/images/spot/spot13.png": [
    {
      x: 50.2,
      y: 41.4,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 59.0,
      y: 48.9,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
    {
      x: 63.1,
      y: 47.5,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
  ],
  "/images/spot/spot14.png": [
    {
      x: 23.4,
      y: 35.6,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 36.6,
      y: 47.7,
      species: "tiur",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla firkant",
    },
    {
      x: 41.9,
      y: 24.2,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 49.2,
      y: 54.1,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 51.3,
      y: 55.3,
      species: "orrhane",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul sirkel",
    },
    {
      x: 66.2,
      y: 52.1,
      species: "tiur",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla firkant",
    },
  ],
  "/images/spot/spot18.png": [
    {
      x: 35.0,
      y: 27.8,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 36.6,
      y: 27.8,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 44.0,
      y: 42.5,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
  ],
  "/images/spot/spot19fog.png": [
    {
      x: 19.1,
      y: 50.2,
      species: "tiur",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla firkant",
    },
    {
      x: 40.3,
      y: 23.8,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 58.0,
      y: 60.3,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 62.6,
      y: 62.3,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
    {
      x: 78.3,
      y: 47.8,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
  ],
  "/images/spot/spot20fog.png": [
    {
      x: 25.0,
      y: 50.9,
      species: "tiur",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla firkant",
    },
    {
      x: 33.1,
      y: 61.0,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 52.9,
      y: 46.5,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 55.2,
      y: 63.1,
      species: "orrhane",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul sirkel",
    },
    {
      x: 85.1,
      y: 64.1,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
  ],
  "/images/spot/spot21.png": [
    {
      x: 16.2,
      y: 46.4,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 18.9,
      y: 54.2,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
    {
      x: 34.1,
      y: 65.4,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 36.9,
      y: 61.1,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 60.4,
      y: 57.8,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
    {
      x: 67.5,
      y: 56.5,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 71.4,
      y: 52.2,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 82.4,
      y: 61.1,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
  ],
  "/images/spot/spot22.png": [
    {
      x: 21.5,
      y: 38.2,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 26.3,
      y: 47.7,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
    {
      x: 36.0,
      y: 52.6,
      species: "tiur",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn firkant",
    },
    {
      x: 38.4,
      y: 54.4,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 64.9,
      y: 49.6,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
    {
      x: 70.3,
      y: 50.3,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 75.4,
      y: 43.9,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 83.6,
      y: 51.5,
      species: "orrhane",
      distanceMinM: 240,
      distanceMaxM: 300,
      note: "grønn sirkel",
    },
  ],
  "/images/spot/spot23.png": [
    {
      x: 45.6,
      y: 26.7,
      species: "tiur",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød firkant",
    },
    {
      x: 53.7,
      y: 19.2,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 58.5,
      y: 34.4,
      species: "orrhane",
      distanceMinM: 110,
      distanceMaxM: 170,
      note: "rød sirkel",
    },
    {
      x: 65.1,
      y: 58.6,
      species: "tiur",
      distanceMinM: 300,
      distanceMaxM: 500,
      note: "gul firkant",
    },
    {
      x: 78.9,
      y: 50.3,
      species: "orrhane",
      distanceMinM: 180,
      distanceMaxM: 230,
      note: "lilla sirkel",
    },
  ],
};

export function perchesForSpotImage(imageSrc: string): SpotPerch[] {
  return SPOT_PERCHES[imageSrc] ?? [];
}

/** Spot landscapes that have hand-authored placement guides. */
export function spotImagesWithPerches(): string[] {
  return Object.keys(SPOT_PERCHES).filter(
    (src) => (SPOT_PERCHES[src]?.length ?? 0) > 0,
  );
}

/** Roll a whole-meter distance inside a perch band. */
export function rollPerchDistanceM(
  perch: Pick<SpotPerch, "distanceMinM" | "distanceMaxM">,
  random: () => number = Math.random,
): number {
  const lo = Math.min(perch.distanceMinM, perch.distanceMaxM);
  const hi = Math.max(perch.distanceMinM, perch.distanceMaxM);
  return lo + Math.floor(random() * (hi - lo + 1));
}
