import type { CatalogDraft, ShopItem } from "./types";
import { isAmmoItem, isCamoItem } from "./types";
import {
  caliberSortIndex,
  projectileTypeSortIndex,
} from "@/lib/ammo/spec";
import { resolveWeightGrams } from "./weights";
import { rifleAverageBestMoa } from "@/lib/rifle/spec";

/**
 * XXL catalog.
 * Prices ≈ Norwegian retail (NOK incl. VAT). Weights in grams via weights map
 * (or inline weightGrams). Ammo requires full ammo spec + internal MOA.
 */
const CATALOG_DRAFT: CatalogDraft[] = [
  // --- LRF ---
  {
    id: "lrf-sig-kilo3000-bdx-10x42",
    category: "lrf",
    brand: "Sig Sauer",
    name: "KILO3000 BDX 10x42",
    priceNok: 15990,
    note: "LRF-kikkert m/BDX Bluetooth. (Ofte kalt 10x40 i slang — korrekt er 10x42.)",
    lrf: {
      hasOnboardBallistics: true,
      ballisticSystem: "BDX + AB Ultralite",
      rangeErrorPercent: 1,
      magnification: 10,
    },
  },
  {
    id: "lrf-biltema-monocular",
    category: "lrf",
    brand: "Biltema",
    name: "Avstandsmåler 6× monokkel",
    priceNok: 1000,
    note: "Ufancy 6×, men måler meter. Primærbehov dekket.",
    lrf: {
      hasOnboardBallistics: false,
      rangeErrorPercent: 3,
      magnification: 6,
    },
  },
  {
    id: "lrf-jula-pocket",
    category: "lrf",
    brand: "Jula",
    name: "Pocket Laser Rangefinder 4×",
    priceNok: 799,
    soldOut: true,
    note: "Golf/jakt-hybrid 4× fra hylla ved grillen. — For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: false,
      rangeErrorPercent: 3,
      magnification: 4,
    },
  },
  {
    id: "lrf-clas-ohlson-golf",
    category: "lrf",
    brand: "Clas Ohlson",
    name: "Golfavstandsmåler 6×",
    priceNok: 1299,
    soldOut: true,
    note: "6× — fungerer på trær også. Offisielt til golf. — For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: false,
      rangeErrorPercent: 3,
      magnification: 6,
    },
  },
  {
    id: "lrf-magasinet-budget-binos",
    category: "lrf",
    brand: "Magasinet",
    name: "Budget 10x42 + «laser»",
    priceNok: 2490,
    soldOut: true,
    note: "Kikkert med tvilsom LRF. Billig, tung, ærlig. — For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: false,
      rangeErrorPercent: 2.5,
    },
  },
  {
    id: "lrf-leica-geovid-r-10x42",
    category: "lrf",
    brand: "Leica",
    name: "Geovid R 10x42",
    priceNok: 22500,
    soldOut: true,
    note: "For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: true,
      ballisticSystem: "EHR / basic ballistic",
      rangeErrorPercent: 1,
    },
  },
  {
    id: "lrf-leica-geovid-r-8x42",
    category: "lrf",
    brand: "Leica",
    name: "Geovid R 8x42",
    priceNok: 22500,
    soldOut: true,
    note: "For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: true,
      ballisticSystem: "EHR / basic ballistic",
      rangeErrorPercent: 1,
    },
  },
  {
    id: "lrf-leica-geovid-pro-10x42",
    category: "lrf",
    brand: "Leica",
    name: "Geovid Pro 10x42",
    priceNok: 36500,
    soldOut: true,
    note: "Applied Ballistics-klasse. — For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: true,
      ballisticSystem: "Applied Ballistics",
      rangeErrorPercent: 1,
    },
  },
  {
    id: "lrf-vortex-fury-hd-5000-10x42",
    category: "lrf",
    brand: "Vortex",
    name: "Fury HD 5000 10x42",
    priceNok: 18990,
    soldOut: true,
    note: "For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: true,
      ballisticSystem: "Applied Ballistics",
      rangeErrorPercent: 1,
    },
  },
  {
    id: "lrf-vortex-ranger-1800",
    category: "lrf",
    brand: "Vortex",
    name: "Ranger 1800 (monokular)",
    priceNok: 4990,
    soldOut: true,
    note: "For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: false,
      rangeErrorPercent: 1,
    },
  },
  {
    id: "lrf-zeiss-victory-rf-10x42",
    category: "lrf",
    brand: "Zeiss",
    name: "Victory RF 10x42",
    priceNok: 39990,
    soldOut: true,
    note: "For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: true,
      ballisticSystem: "Onboard ballistic",
      rangeErrorPercent: 1,
    },
  },
  {
    id: "lrf-zeiss-victory-rf-8x42",
    category: "lrf",
    brand: "Zeiss",
    name: "Victory RF 8x42",
    priceNok: 38990,
    soldOut: true,
    note: "For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: true,
      ballisticSystem: "Onboard ballistic",
      rangeErrorPercent: 1,
    },
  },
  {
    id: "lrf-kahles-helia-rf-10x42",
    category: "lrf",
    brand: "Kahles",
    name: "Helia RF 10x42",
    priceNok: 27990,
    soldOut: true,
    note: "For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: true,
      ballisticSystem: "Onboard ballistic",
      rangeErrorPercent: 1,
    },
  },
  {
    id: "lrf-leupold-rx-2800-tbr-w",
    category: "lrf",
    brand: "Leupold",
    name: "RX-2800 TBR/W",
    priceNok: 8490,
    soldOut: true,
    note: "Kompakt monokular LRF. — For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: true,
      ballisticSystem: "TBR/W",
      rangeErrorPercent: 1,
    },
  },
  {
    id: "lrf-leupold-bx-4-rangeguide-10x42",
    category: "lrf",
    brand: "Leupold",
    name: "BX-4 RangeGuide 10x42",
    priceNok: 21990,
    soldOut: true,
    note: "For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: true,
      ballisticSystem: "RangeGuide ballistic",
      rangeErrorPercent: 1,
    },
  },
  {
    id: "lrf-burris-signature-lrf-10x42",
    category: "lrf",
    brand: "Burris",
    name: "Signature LRF 10x42",
    priceNok: 14990,
    soldOut: true,
    note: "For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: false,
      rangeErrorPercent: 1.5,
    },
  },
  {
    id: "lrf-swarovski-el-range-10x42",
    category: "lrf",
    brand: "Swarovski",
    name: "EL Range 10x42",
    priceNok: 42990,
    soldOut: true,
    note: "For tiden utsolgt.",
    lrf: {
      hasOnboardBallistics: true,
      ballisticSystem: "Tracking Assistant / ballistic",
      rangeErrorPercent: 1,
    },
  },

  // --- Thermal spotters ---
  {
    id: "thermal-hikmicro-lynx-le10",
    category: "thermal",
    brand: "Hikmicro",
    name: "Lynx LE10",
    priceNok: 6490,
    note: "Håndholdt termisk spotter. 256×192 — ser varme, ikke detaljer.",
    thermal: {
      pixelFactor: 6,
      magnification: 2.8,
      timeFactor: 20,
    },
  },
  {
    id: "thermal-hikmicro-condor-cq35-lrf",
    category: "thermal",
    brand: "Hikmicro",
    name: "Condor CQ35 LRF",
    priceNok: 29900,
    note: "Termisk kikkert m/integrert avstandsmåler. 384×288 sensor.",
    thermal: {
      pixelFactor: 3,
      magnification: 3.5,
      timeFactor: 30,
      hasIntegratedLrf: true,
      rangeErrorPercent: 1.5,
    },
  },

  // --- Scopes ---
  {
    id: "scope-nf-nx8-4-32-moa",
    category: "scope",
    brand: "Nightforce",
    name: "NX8 4-32x50 F2 MOA",
    priceNok: 28990,
    note: "MOA-klikk / second focal plane-varianter.",
    scope: {
      minZoom: 4,
      maxZoom: 32,
      clickUnit: "MOA",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.12,
    },
  },
  {
    id: "scope-nf-nx8-4-32-mrad",
    category: "scope",
    brand: "Nightforce",
    name: "NX8 4-32x50 F1 MIL-R MRAD",
    priceNok: 31990,
    note: "FFP · MIL-R retikkel.",
    scope: {
      minZoom: 4,
      maxZoom: 32,
      focalPlane: "FFP",
      reticleId: "nightforce-mil-r",
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.12,
    },
  },
  {
    id: "scope-nf-atacr-5-25-f1",
    category: "scope",
    brand: "Nightforce",
    name: "ATACR 5-25x56 F1 MRAD",
    priceNok: 42990,
    scope: {
      minZoom: 5,
      maxZoom: 25,
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.08,
    },
  },
  {
    id: "scope-nf-atacr-7-35-f1",
    category: "scope",
    brand: "Nightforce",
    name: "ATACR 7-35x56 F1 MRAD",
    priceNok: 48990,
    scope: {
      minZoom: 7,
      maxZoom: 35,
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.08,
    },
  },
  {
    id: "scope-zco-527-mct",
    category: "scope",
    brand: "Zero Compromise",
    name: "ZCO 5-27x56 MCT",
    priceNok: 54990,
    note: "FFP · MPCT mil-retikkel · 0.1 mil klikk.",
    scope: {
      minZoom: 5,
      maxZoom: 27,
      focalPlane: "FFP",
      reticleId: "zco-527-mpct",
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.05,
    },
  },
  {
    id: "scope-element-titan-5-20-mrad",
    category: "scope",
    brand: "Element Optics",
    name: "Titan 5-20x50 MRAD",
    priceNok: 12990,
    scope: {
      minZoom: 5,
      maxZoom: 20,
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.22,
    },
  },
  {
    id: "scope-element-theos-5-25-mrad",
    category: "scope",
    brand: "Element Optics",
    name: "Theos 5-25x56 MRAD",
    priceNok: 18990,
    scope: {
      minZoom: 5,
      maxZoom: 25,
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.15,
    },
  },
  {
    id: "scope-leupold-mk5hd-5-25-mrad",
    category: "scope",
    brand: "Leupold",
    name: "Mark 5HD 5-25x56 MRAD",
    priceNok: 34990,
    scope: {
      minZoom: 5,
      maxZoom: 25,
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.12,
    },
  },
  {
    id: "scope-kahles-k318i-3-18-mrad",
    category: "scope",
    brand: "Kahles",
    name: "K318i 3.5-18x50 MRAD",
    priceNok: 32990,
    note: "FFP · SKMR mil-retikkel · 0.1 mil klikk.",
    scope: {
      minZoom: 3.5,
      maxZoom: 18,
      focalPlane: "FFP",
      reticleId: "kahles",
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.1,
    },
  },
  {
    id: "scope-kahles-k525i-5-25-mrad",
    category: "scope",
    brand: "Kahles",
    name: "K525i 5-25x56 MRAD",
    priceNok: 42990,
    note: "FFP · SKMR mil-retikkel · 0.1 mil klikk.",
    scope: {
      minZoom: 5,
      maxZoom: 25,
      focalPlane: "FFP",
      reticleId: "kahles",
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.08,
    },
  },
  {
    id: "scope-kahles-k624i-6-24-mrad",
    category: "scope",
    brand: "Kahles",
    name: "K624i 6-24x56 MRAD",
    priceNok: 38990,
    note: "FFP · SKMR mil-retikkel · 0.1 mil klikk.",
    scope: {
      minZoom: 6,
      maxZoom: 24,
      focalPlane: "FFP",
      reticleId: "kahles",
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.1,
    },
  },
  {
    id: "scope-kahles-k16i-1-6",
    category: "scope",
    brand: "Kahles",
    name: "K16i 1-6x24",
    priceNok: 21990,
    note: "LPVO · SKMR-grafikk (SFP-skala) · Kahles topper typisk rundt 5-25 / 6-24.",
    scope: {
      minZoom: 1,
      maxZoom: 6,
      reticleId: "kahles",
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.15,
    },
  },
  {
    id: "scope-zeiss-lrp-s5-6-36-mrad",
    category: "scope",
    brand: "Zeiss",
    name: "LRP S5 6-36x56 MRAD",
    priceNok: 44990,
    scope: {
      minZoom: 6,
      maxZoom: 36,
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.08,
    },
  },
  {
    id: "scope-sb-pmii-5-25-mrad",
    category: "scope",
    brand: "Schmidt & Bender",
    name: "PM II 5-25x56 MRAD",
    priceNok: 42990,
    note: "FFP · SB mil-retikkel · 0.1 mil klikk.",
    scope: {
      minZoom: 5,
      maxZoom: 25,
      focalPlane: "FFP",
      reticleId: "sb",
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.06,
    },
  },
  {
    id: "scope-sb-pmii-3-20-mrad",
    category: "scope",
    brand: "Schmidt & Bender",
    name: "PM II 3-20x50 MRAD",
    priceNok: 38990,
    note: "FFP · SB mil-retikkel · 0.1 mil klikk.",
    scope: {
      minZoom: 3,
      maxZoom: 20,
      focalPlane: "FFP",
      reticleId: "sb",
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.08,
    },
  },
  {
    id: "scope-sb-pmii-high-power-5-45",
    category: "scope",
    brand: "Schmidt & Bender",
    name: "PM II High Power 5-45x56 MRAD",
    priceNok: 59990,
    note: "FFP · SB mil-retikkel · 0.1 mil klikk.",
    scope: {
      minZoom: 5,
      maxZoom: 45,
      focalPlane: "FFP",
      reticleId: "sb",
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.05,
    },
  },
  {
    id: "scope-burris-fullfield-3-9x40",
    category: "scope",
    brand: "Burris",
    name: "Fullfield E1 3-9x40",
    priceNok: 3490,
    note: "Klassisk jaktkikkert med klikk.",
    scope: {
      minZoom: 3,
      maxZoom: 9,
      clickUnit: "MOA",
      clickErrorPercent: 5,
      zeroRetentionInaccuracy: 0.4,
    },
  },
  {
    id: "scope-burris-eliminator-6",
    category: "scope",
    brand: "Burris",
    name: "Eliminator 6",
    priceNok: 24990,
    note: "Digital LRF-scope — holdover på display, ikke tradisjonelle turrets for drop.",
    scope: {
      minZoom: 4,
      maxZoom: 20,
      clickUnit: "MOA",
      clickErrorPercent: 2,
      zeroRetentionInaccuracy: 0.25,
    },
  },
  {
    id: "scope-vortex-razor-gen3-6-36-mrad",
    category: "scope",
    brand: "Vortex",
    name: "Razor HD Gen III 6-36x56 MRAD",
    priceNok: 39990,
    scope: {
      minZoom: 6,
      maxZoom: 36,
      clickUnit: "MRAD",
      clickErrorPercent: 0,
      zeroRetentionInaccuracy: 0.1,
    },
  },
  {
    id: "scope-vortex-viper-pst-gen2-5-25-mrad",
    category: "scope",
    brand: "Vortex",
    name: "Viper PST Gen II 5-25x50 MRAD",
    priceNok: 14990,
    scope: {
      minZoom: 5,
      maxZoom: 25,
      clickUnit: "MRAD",
      clickErrorPercent: 3,
      zeroRetentionInaccuracy: 0.2,
    },
  },
  {
    id: "scope-biltema-3-9x40",
    category: "scope",
    brand: "Biltema",
    name: "3-9x40 Jaktkikkert",
    priceNok: 599,
    note: "Klikk som føles som Lego. Virker på 100 m. Nesten.",
    scope: {
      minZoom: 3,
      maxZoom: 9,
      clickUnit: "MOA",
      clickErrorPercent: 10,
      zeroRetentionInaccuracy: 0.85,
    },
  },
  {
    id: "scope-jula-4-12x40",
    category: "scope",
    brand: "Jula",
    name: "4-12x40",
    priceNok: 899,
    scope: {
      minZoom: 4,
      maxZoom: 12,
      clickUnit: "MOA",
      clickErrorPercent: 10,
      zeroRetentionInaccuracy: 0.7,
    },
  },
  {
    id: "scope-clas-ohlson-4x32",
    category: "scope",
    brand: "Clas Ohlson",
    name: "4x32 Compact",
    priceNok: 449,
    note: "Luftgevær-vibber. Til CZ452 før du har råd til mer.",
    scope: {
      minZoom: 4,
      maxZoom: 4,
      clickUnit: "MOA",
      clickErrorPercent: 10,
      zeroRetentionInaccuracy: 1.1,
    },
  },

  // --- Suppressors ---
  {
    id: "sup-svemko-hunter-1",
    category: "suppressor",
    brand: "Svemko",
    name: "Hunter 1.0 Standard",
    priceNok: 7500,
  },
  {
    id: "sup-svemko-magnum-1",
    category: "suppressor",
    brand: "Svemko",
    name: "Magnum 1.0 Standard",
    priceNok: 6900,
  },
  {
    id: "sup-svemko-pure-m",
    category: "suppressor",
    brand: "Svemko",
    name: "Pure M",
    priceNok: 9800,
  },
  {
    id: "sup-svemko-genesis-30",
    category: "suppressor",
    brand: "Svemko",
    name: "Genesis .30 Titan",
    priceNok: 24000,
    note: "Premium full-titan langhold.",
  },
  {
    id: "sup-hausken-jd184-xtrm",
    category: "suppressor",
    brand: "Hausken",
    name: "JD184 XTRM MK2",
    priceNok: 4790,
  },
  {
    id: "sup-hausken-jd224-xtrm",
    category: "suppressor",
    brand: "Hausken",
    name: "JD224 XTRM MK2",
    priceNok: 5490,
  },
  {
    id: "sup-hausken-jd151-xtrm",
    category: "suppressor",
    brand: "Hausken",
    name: "JD151 XTRM MK2",
    priceNok: 4250,
  },
  {
    id: "sup-hausken-jd252-xtrm",
    category: "suppressor",
    brand: "Hausken",
    name: "JD252 XTRM MK2",
    priceNok: 6490,
  },
  {
    id: "sup-atec-h2",
    category: "suppressor",
    brand: "A-TEC",
    name: "H2 (modulær)",
    priceNok: 3950,
  },
  {
    id: "sup-atec-optima-50",
    category: "suppressor",
    brand: "A-TEC",
    name: "Optima 50",
    priceNok: 4490,
  },
  {
    id: "sup-atec-nordic",
    category: "suppressor",
    brand: "A-TEC",
    name: "Nordic / Hertz",
    priceNok: 3180,
  },
  {
    id: "sup-atec-wave-22",
    category: "suppressor",
    brand: "A-TEC",
    name: "Wave .22 LR",
    priceNok: 799,
    note: "Passer onkelens CZ452 / rimfire.",
  },
  {
    id: "sup-freyr-devik-3d-231",
    category: "suppressor",
    brand: "Freyr & Devik",
    name: "Ultimate Silence 3D-231",
    priceNok: 5400,
  },
  {
    id: "sup-freyr-devik-3d-131",
    category: "suppressor",
    brand: "Freyr & Devik",
    name: "Ultimate Silence 3D-131",
    priceNok: 4800,
  },
  {
    id: "sup-tronrud-gen1",
    category: "suppressor",
    brand: "Tronrud Engineering",
    name: "Gen 1 Titan",
    priceNok: 8900,
    note: "Klassisk norsk titan-demper (Gen 1).",
  },
  {
    id: "sup-vanguard-titan",
    category: "suppressor",
    brand: "Vanguard",
    name: "Titan (Tronrud-arv)",
    priceNok: 9900,
    note: "Etterfølger-linje etter Tronrud titan.",
  },
  {
    id: "sup-aimsport-triton",
    category: "suppressor",
    brand: "Aimsport",
    name: "Triton 50",
    priceNok: 4290,
  },
  {
    id: "sup-stalon-victor",
    category: "suppressor",
    brand: "Stalon",
    name: "Victor L",
    priceNok: 3990,
  },
  {
    id: "sup-biltema-22-can",
    category: "suppressor",
    brand: "Biltema",
    name: ".22 «lyddemper»",
    priceNok: 399,
    note: "Budget rimfire-can. Bedre enn ingenting på ekornbanen.",
  },
  {
    id: "sup-jula-economy-30",
    category: "suppressor",
    brand: "Jula",
    name: "Economy .30 demper",
    priceNok: 1490,
    note: "Tung, stål, ærlig demping. Ikke titan-drømmen.",
  },

  // --- Stocks ---
  {
    id: "stock-grs-berserk-t3x",
    category: "stock",
    brand: "GRS",
    name: "Berserk (Tikka T3x)",
    priceNok: 5990,
    fits: "Tikka T3x",
    note: "GRS lager ikke til alle våpen — sjekk inlet.",
    stock: {
      moaDelta: -0.06,
    },
  },
  {
    id: "stock-grs-hunter-light-t3x",
    category: "stock",
    brand: "GRS",
    name: "Hunter Light (Tikka T3x)",
    priceNok: 7490,
    fits: "Tikka T3x",
    stock: {
      moaDelta: -0.04,
    },
  },
  {
    id: "stock-grs-bifrost-sako85",
    category: "stock",
    brand: "GRS",
    name: "Bifrost (Sako 85)",
    priceNok: 8990,
    fits: "Sako 85",
    stock: {
      moaDelta: -0.07,
    },
  },
  {
    id: "stock-grs-sportsmann-rem700",
    category: "stock",
    brand: "GRS",
    name: "Sporter / Sportsmann (Rem 700 SA)",
    priceNok: 6490,
    fits: "Remington 700 SA",
    stock: {
      moaDelta: -0.05,
    },
  },
  {
    id: "stock-mdt-lss-xl-gen2-t3x",
    category: "stock",
    brand: "MDT",
    name: "LSS-XL Gen2 Chassis (Tikka)",
    priceNok: 8990,
    fits: "Tikka T3x",
    note: "Konkurranse/jakt-chassis — ikke alle våpen har MDT-valg.",
    stock: {
      moaDelta: -0.08,
    },
  },
  {
    id: "stock-mdt-acc-elite-rem700",
    category: "stock",
    brand: "MDT",
    name: "ACC Elite Chassis (Rem 700)",
    priceNok: 14990,
    fits: "Remington 700",
    stock: {
      moaDelta: -0.12,
    },
  },
  {
    id: "stock-mdt-hnt26-rem700",
    category: "stock",
    brand: "MDT",
    name: "HNT26 Chassis (Rem 700 SA)",
    priceNok: 15990,
    fits: "Remington 700 SA",
    note: "Ultralett jakt-chassis (carbon/magnesium, ~740 g). V-bedding, AICS-magasin.",
    stock: {
      moaDelta: -0.1,
    },
  },
  {
    id: "stock-mdt-ors-t3x",
    category: "stock",
    brand: "MDT",
    name: "ORS Chassis Carbon (Tikka)",
    priceNok: 18990,
    fits: "Tikka T3x",
    stock: {
      moaDelta: -0.1,
    },
  },
  {
    id: "stock-mcmillan-a5-rem700",
    category: "stock",
    brand: "McMillan",
    name: "A5 (Rem 700 SA)",
    priceNok: 12990,
    fits: "Remington 700 SA",
    note: "Utvalgte modeller / custom inlet.",
    stock: {
      moaDelta: -0.1,
    },
  },
  {
    id: "stock-mcmillan-game-hunter-sako",
    category: "stock",
    brand: "McMillan",
    name: "Game Hunter (Sako / custom)",
    priceNok: 13990,
    fits: "Sako (utvalgte)",
    stock: {
      moaDelta: -0.08,
    },
  },
  {
    id: "stock-biltema-synthetic-rem700",
    category: "stock",
    brand: "Biltema",
    name: "Syntetisk Rem 700-stokk",
    priceNok: 799,
    fits: "Remington 700 SA",
    note: "Passer «nesten». Fil og håp.",
    stock: {
      moaDelta: 0.03,
    },
  },
  {
    id: "stock-jula-plastic-tikka",
    category: "stock",
    brand: "Jula",
    name: "Plaststokk Tikka-ish",
    priceNok: 699,
    fits: "Tikka T3x (omtrent)",
    stock: {
      moaDelta: 0.04,
    },
  },

  // --- Rifles ---
  {
    id: "rifle-cz452",
    category: "rifle",
    brand: "CZ",
    name: "452 American .22 LR",
    priceNok: 0,
    caliber: ".22 LR",
    note: "Onkelens arv — ikke til salgs. Med billig Biltema 3-9×40 på.",
    rifle: {
      averageBestAccuracyMoa: 0.55,
    },
  },
  {
    id: "rifle-tikka-t3x-lite",
    category: "rifle",
    brand: "Tikka",
    name: "T3x Lite",
    priceNok: 16990,
    caliber: "flere (bla. 6,5×55 / .308 / 6,5 CM)",
    rifle: {
      averageBestAccuracyMoa: 0.6,
    },
  },
  {
    id: "rifle-tikka-t3x-super-varminter",
    category: "rifle",
    brand: "Tikka",
    name: "T3x Super Varmint",
    priceNok: 21990,
    caliber: "flere",
    rifle: {
      averageBestAccuracyMoa: 0.35,
    },
  },
  {
    id: "rifle-tikka-t3x-tac-a1",
    category: "rifle",
    brand: "Tikka",
    name: "T3x TACT A1",
    priceNok: 37190,
    caliber: "6,5 Creedmoor / .308 m.fl.",
    rifle: {
      averageBestAccuracyMoa: 0.35,
    },
  },
  {
    id: "rifle-sako-s20",
    category: "rifle",
    brand: "Sako",
    name: "S20 Hunter",
    priceNok: 28990,
    caliber: "flere",
    rifle: {
      averageBestAccuracyMoa: 0.45,
    },
  },
  {
    id: "rifle-sako-85-finnlight",
    category: "rifle",
    brand: "Sako",
    name: "85 Finnlight II",
    priceNok: 32990,
    caliber: "flere",
    rifle: {
      averageBestAccuracyMoa: 0.5,
    },
  },
  {
    id: "rifle-sako-85-carbonwolf",
    category: "rifle",
    brand: "Sako",
    name: "85 Carbon Wolf",
    priceNok: 42190,
    caliber: "6,5×55",
    note: "Lett carbon-stokk m/justerbar kinnstøtte — toppjakt-klassiker i 6,5×55.",
    rifle: {
      averageBestAccuracyMoa: 0.4,
    },
  },
  {
    id: "rifle-carbonwolf-berillium",
    category: "rifle",
    brand: "CarbonWölf",
    name: "Berillium Level",
    priceNok: 58900,
    caliber: "6,5×55",
    note: "Berillium-tier Carbon Wolf-bygg — lettere chassis, strammere gulv.",
    rifle: {
      averageBestAccuracyMoa: 0.3,
    },
  },
  {
    id: "rifle-sako-90-peak",
    category: "rifle",
    brand: "Sako",
    name: "90 Peak",
    priceNok: 35990,
    caliber: "flere",
    rifle: {
      averageBestAccuracyMoa: 0.4,
    },
  },
  {
    id: "rifle-sauer-200str",
    category: "rifle",
    brand: "Sauer",
    name: "200 STR",
    priceNok: 45990,
    caliber: "flere (NLS-favoritt)",
    note: "Norsk konkurranseklassiker.",
    rifle: {
      averageBestAccuracyMoa: 0.28,
    },
  },
  {
    id: "rifle-sauer-404",
    category: "rifle",
    brand: "Sauer",
    name: "404 Synchro XT",
    priceNok: 42990,
    caliber: "flere",
    rifle: {
      averageBestAccuracyMoa: 0.45,
    },
  },
  {
    id: "rifle-rem-700-sps",
    category: "rifle",
    brand: "Remington",
    name: "700 SPS",
    priceNok: 12990,
    caliber: ".308 / .30-06 m.fl.",
    rifle: {
      averageBestAccuracyMoa: 0.85,
    },
  },
  {
    id: "rifle-rem-700-sa-65cm",
    category: "rifle",
    brand: "Remington",
    name: "700 SA",
    priceNok: 15990,
    caliber: "6,5 Creedmoor",
    note: "Short action Rem 700 — passer MDT HNT26 og andre Rem 700 SA-chassis.",
    rifle: {
      averageBestAccuracyMoa: 0.55,
    },
  },
  {
    id: "rifle-rem-700-sa-hansen-custom",
    category: "rifle",
    brand: "Hansen Custom",
    name: "Rem700 SA",
    priceNok: 48500,
    caliber: "6,5 Creedmoor",
    note: "Hansen Custom Rem 700 SA — samme precision-gulv som Sauer 200 STR. Passer Rem 700 SA-chassis (HNT26).",
    rifle: {
      averageBestAccuracyMoa: 0.28,
    },
  },
  {
    id: "rifle-rem-700-aac-sd",
    category: "rifle",
    brand: "Remington",
    name: "700 AAC-SD / long range",
    priceNok: 18990,
    caliber: ".308 / 6,5 CM",
    rifle: {
      averageBestAccuracyMoa: 0.55,
    },
  },
  {
    id: "rifle-bergara-b14-hmr",
    category: "rifle",
    brand: "Bergara",
    name: "B-14 HMR",
    priceNok: 16990,
    caliber: "6,5 Creedmoor / .308",
    rifle: {
      averageBestAccuracyMoa: 0.4,
    },
  },
  {
    id: "rifle-bergara-b14-ridge",
    category: "rifle",
    brand: "Bergara",
    name: "B-14 Ridge",
    priceNok: 13990,
    caliber: "flere",
    rifle: {
      averageBestAccuracyMoa: 0.55,
    },
  },
  {
    id: "rifle-howa-1500-hs",
    category: "rifle",
    brand: "Howa",
    name: "1500 Hogue / HS Precision",
    priceNok: 11990,
    caliber: "flere",
    rifle: {
      averageBestAccuracyMoa: 0.65,
    },
  },
  {
    id: "rifle-ruger-american-predator",
    category: "rifle",
    brand: "Ruger",
    name: "American Predator",
    priceNok: 9990,
    caliber: "6,5 Creedmoor / .308",
    rifle: {
      averageBestAccuracyMoa: 0.75,
    },
  },
  {
    id: "rifle-ruger-american-ranch-300blk",
    category: "rifle",
    brand: "Ruger",
    name: "American Ranch .300 BLK",
    priceNok: 11990,
    caliber: ".300 BLK",
    note: "Kort pipe — laget for subsonisk .300 BLK med lyddemper.",
    rifle: {
      averageBestAccuracyMoa: 0.9,
    },
  },
  {
    id: "rifle-browning-xbolt-pro",
    category: "rifle",
    brand: "Browning",
    name: "X-Bolt Pro Carbon",
    priceNok: 28990,
    caliber: "flere",
    rifle: {
      averageBestAccuracyMoa: 0.45,
    },
  },
  {
    id: "rifle-blaser-r8",
    category: "rifle",
    brand: "Blaser",
    name: "R8 Professional",
    priceNok: 54990,
    caliber: "utskiftbare piper",
    rifle: {
      averageBestAccuracyMoa: 0.5,
    },
  },
  {
    id: "rifle-ai-at-x",
    category: "rifle",
    brand: "Accuracy International",
    name: "AT-X",
    priceNok: 89990,
    caliber: ".308 / 6,5 CM m.fl.",
    rifle: {
      averageBestAccuracyMoa: 0.25,
    },
  },
  {
    id: "rifle-cz455",
    category: "rifle",
    brand: "CZ",
    name: "455 Synthetic .22 LR",
    priceNok: 6990,
    caliber: ".22 LR",
    rifle: {
      averageBestAccuracyMoa: 0.8,
    },
  },
  {
    id: "rifle-cz457",
    category: "rifle",
    brand: "CZ",
    name: "457 Varmint MTR .22 LR",
    priceNok: 11990,
    caliber: ".22 LR",
    rifle: {
      averageBestAccuracyMoa: 0.4,
    },
  },
  {
    id: "rifle-magasinet-budget-308",
    category: "rifle",
    brand: "Magasinet",
    name: "Budget Hunter .308",
    priceNok: 7990,
    caliber: ".308 Win",
    note: "Ukjent fabrikk, kjent pris. 1 MOA? Vi får se.",
    rifle: {
      averageBestAccuracyMoa: 1.25,
    },
  },
  {
    id: "rifle-jula-youth-22",
    category: "rifle",
    brand: "Jula",
    name: "Youth .22 bolt",
    priceNok: 2990,
    caliber: ".22 LR",
    note: "Billigere enn onkelens CZ. Verre treffbilde.",
    rifle: {
      averageBestAccuracyMoa: 1.5,
    },
  },

  // --- Ammo ---
  // maxAchievableMoa is INTERNAL (placeholders — tune later).
  // damageFactor: low = less meat ruin, needs better placement (not "weak").
  {
    id: "ammo-norma-65x55-fmj",
    category: "ammo",
    brand: "Norma",
    name: "FMJ Training 6,5g",
    priceNok: 420,
    unitLabel: "eske 50",
    ammo: {
      caliber: "6,5×55",
      projectileType: "FMJ",
      v0: 850,
      bc: 0.28,
      bcModel: "G1",
      damageFactor: 0.22,
      maxAchievableMoa: 1.0,
    },
  },
  {
    id: "ammo-lapua-65x55-scenar",
    category: "ammo",
    brand: "Lapua",
    name: "Scenar 139gr OTM",
    priceNok: 890,
    unitLabel: "eske 20",
    ammo: {
      caliber: "6,5×55",
      projectileType: "OTM",
      v0: 800,
      bc: 0.489,
      bcModel: "G1",
      damageFactor: 0.18,
      maxAchievableMoa: 0.25,
    },
  },
  {
    id: "ammo-norma-65x55-black-diamond",
    category: "ammo",
    brand: "Norma",
    name: "Black Diamond Fält 130gr",
    priceNok: 980,
    unitLabel: "eske 20",
    note: "Norma Black Diamond Fält — 130gr, 900 m/s.",
    ammo: {
      caliber: "6,5×55",
      projectileType: "OTM",
      v0: 900,
      bc: 0.5,
      bcModel: "G1",
      damageFactor: 0.18,
      maxAchievableMoa: 0.28,
    },
  },
  {
    id: "ammo-sako-65x55-gamehead",
    category: "ammo",
    brand: "Sako",
    name: "Gamehead 140gr",
    priceNok: 620,
    unitLabel: "eske 20",
    ammo: {
      caliber: "6,5×55",
      projectileType: "SP",
      v0: 820,
      bc: 0.35,
      bcModel: "G1",
      damageFactor: 0.62,
      maxAchievableMoa: 0.5,
    },
  },
  {
    id: "ammo-sako-65x55-speedhead",
    category: "ammo",
    brand: "Sako",
    name: "Speedhead 120gr",
    priceNok: 640,
    unitLabel: "eske 20",
    ammo: {
      caliber: "6,5×55",
      projectileType: "SP",
      v0: 870,
      bc: 0.3,
      bcModel: "G1",
      damageFactor: 0.58,
      maxAchievableMoa: 0.5,
    },
  },
  {
    id: "ammo-norma-65x55-orca",
    category: "ammo",
    brand: "Norma",
    name: "Oryx 10,1g / 156gr",
    priceNok: 690,
    unitLabel: "eske 20",
    ammo: {
      caliber: "6,5×55",
      projectileType: "SP",
      v0: 800,
      bc: 0.35,
      bcModel: "G1",
      damageFactor: 0.72,
      maxAchievableMoa: 0.75,
    },
  },
  {
    id: "ammo-norma-65cm-fmj",
    category: "ammo",
    brand: "Norma",
    name: "FMJ Training",
    priceNok: 450,
    unitLabel: "eske 50",
    ammo: {
      caliber: "6,5 Creedmoor",
      projectileType: "FMJ",
      v0: 850,
      bc: 0.3,
      bcModel: "G1",
      damageFactor: 0.22,
      maxAchievableMoa: 0.9,
    },
  },
  {
    id: "ammo-lapua-65cm-scenar-l",
    category: "ammo",
    brand: "Lapua",
    name: "Scenar-L 136gr OTM",
    priceNok: 950,
    unitLabel: "eske 20",
    ammo: {
      caliber: "6,5 Creedmoor",
      projectileType: "OTM",
      v0: 850,
      bc: 0.508,
      bcModel: "G1",
      damageFactor: 0.18,
      maxAchievableMoa: 0.25,
    },
  },
  {
    id: "ammo-hornady-65cm-eldm",
    category: "ammo",
    brand: "Hornady",
    name: "ELD Match 147gr",
    priceNok: 720,
    unitLabel: "eske 20",
    ammo: {
      caliber: "6,5 Creedmoor",
      projectileType: "OTM",
      v0: 820,
      bc: 0.697,
      bcModel: "G1",
      damageFactor: 0.2,
      maxAchievableMoa: 0.3,
    },
  },
  {
    id: "ammo-federal-65cm-goldmedal",
    category: "ammo",
    brand: "Federal",
    name: "Gold Medal Berger 130gr OTM",
    priceNok: 880,
    unitLabel: "eske 20",
    ammo: {
      caliber: "6,5 Creedmoor",
      projectileType: "OTM",
      v0: 875,
      bc: 0.56,
      bcModel: "G1",
      damageFactor: 0.19,
      maxAchievableMoa: 0.28,
    },
  },
  {
    id: "ammo-norma-65cm-black-diamond",
    category: "ammo",
    brand: "Norma",
    name: "Black Diamond Line 143gr",
    priceNok: 990,
    unitLabel: "eske 20",
    ammo: {
      caliber: "6,5 Creedmoor",
      projectileType: "OTM",
      v0: 845,
      bc: 0.55,
      bcModel: "G1",
      damageFactor: 0.18,
      maxAchievableMoa: 0.27,
    },
  },
  {
    id: "ammo-norma-65cm-bondstrike",
    category: "ammo",
    brand: "Norma",
    name: "Bondstrike 143gr",
    priceNok: 790,
    unitLabel: "eske 20",
    ammo: {
      caliber: "6,5 Creedmoor",
      projectileType: "SP",
      v0: 840,
      bc: 0.5,
      bcModel: "G1",
      damageFactor: 0.68,
      maxAchievableMoa: 0.55,
    },
  },
  {
    id: "ammo-norma-223-fmj",
    category: "ammo",
    brand: "Norma",
    name: "FMJ 55gr",
    priceNok: 390,
    unitLabel: "eske 50",
    ammo: {
      caliber: ".223 Rem",
      projectileType: "FMJ",
      v0: 950,
      bc: 0.243,
      bcModel: "G1",
      damageFactor: 0.25,
      maxAchievableMoa: 1.0,
    },
  },
  {
    id: "ammo-lapua-223-scenar",
    category: "ammo",
    brand: "Lapua",
    name: "Scenar 69gr OTM",
    priceNok: 640,
    unitLabel: "eske 20",
    ammo: {
      caliber: ".223 Rem",
      projectileType: "OTM",
      v0: 900,
      bc: 0.341,
      bcModel: "G1",
      damageFactor: 0.2,
      maxAchievableMoa: 0.3,
    },
  },
  {
    id: "ammo-sako-223-gamehead",
    category: "ammo",
    brand: "Sako",
    name: "Gamehead 50gr",
    priceNok: 480,
    unitLabel: "eske 20",
    ammo: {
      caliber: ".223 Rem",
      projectileType: "SP",
      v0: 980,
      bc: 0.2,
      bcModel: "G1",
      damageFactor: 0.7,
      maxAchievableMoa: 0.6,
    },
  },
  {
    id: "ammo-hornady-300blk-subsonic",
    category: "ammo",
    brand: "Hornady",
    name: "Sub-X 190gr .300 BLK",
    priceNok: 549,
    unitLabel: "eske 20",
    note: "Subsonisk — markant mer fall. Med lyddemper: nesten lydløs (fugler flusher ikke).",
    ammo: {
      caliber: ".300 BLK",
      projectileType: "SP",
      v0: 305,
      bc: 0.55,
      bcModel: "G1",
      damageFactor: 0.62,
      maxAchievableMoa: 0.75,
      subsonic: true,
    },
  },
  {
    id: "ammo-cci-22lr-standard",
    category: "ammo",
    brand: "CCI",
    name: "Standard Velocity .22 LR",
    priceNok: 189,
    unitLabel: "eske 50",
    note: "Rimfire til CZ452 — grei start-ammo.",
    ammo: {
      caliber: ".22 LR",
      projectileType: "FMJ",
      v0: 327,
      bc: 0.12,
      bcModel: "G1",
      damageFactor: 0.35,
      maxAchievableMoa: 0.85,
    },
  },
  {
    id: "ammo-eley-22lr-match",
    category: "ammo",
    brand: "Eley",
    name: "Tenex / Match .22 LR",
    priceNok: 420,
    unitLabel: "eske 50",
    ammo: {
      caliber: ".22 LR",
      projectileType: "OTM",
      v0: 331,
      bc: 0.15,
      bcModel: "G1",
      damageFactor: 0.28,
      maxAchievableMoa: 0.35,
    },
  },
  {
    id: "ammo-lapua-22lr-center-x",
    category: "ammo",
    brand: "Lapua",
    name: "Center-X .22 LR",
    priceNok: 390,
    unitLabel: "eske 50",
    ammo: {
      caliber: ".22 LR",
      projectileType: "OTM",
      v0: 327,
      bc: 0.15,
      bcModel: "G1",
      damageFactor: 0.28,
      maxAchievableMoa: 0.4,
    },
  },
  {
    id: "ammo-norma-22lr-hunter",
    category: "ammo",
    brand: "Norma",
    name: "Hunter .22 LR",
    priceNok: 149,
    unitLabel: "eske 50",
    ammo: {
      caliber: ".22 LR",
      projectileType: "SP",
      v0: 380,
      bc: 0.12,
      bcModel: "G1",
      damageFactor: 0.55,
      maxAchievableMoa: 1.2,
    },
  },
  {
    id: "ammo-cci-22lr-subsonic",
    category: "ammo",
    brand: "CCI",
    name: "Subsonic HP .22 LR",
    priceNok: 229,
    unitLabel: "eske 50",
    note: "Lav utgangshastighet — dårligere kulebane. Med lyddemper: nesten lydløs (fugler flusher ikke).",
    ammo: {
      caliber: ".22 LR",
      projectileType: "SP",
      v0: 305,
      bc: 0.14,
      bcModel: "G1",
      damageFactor: 0.45,
      maxAchievableMoa: 0.95,
      subsonic: true,
    },
  },
  {
    id: "ammo-hornady-17hmr-varmint",
    category: "ammo",
    brand: "Hornady",
    name: "V-MAX 17gr",
    priceNok: 289,
    unitLabel: "eske 50",
    ammo: {
      caliber: ".17 HMR",
      projectileType: "SP",
      v0: 777,
      bc: 0.125,
      bcModel: "G1",
      damageFactor: 0.75,
      maxAchievableMoa: 0.85,
    },
  },
  {
    id: "ammo-cci-17hmr-tnt",
    category: "ammo",
    brand: "CCI",
    name: "TNT 17gr",
    priceNok: 269,
    unitLabel: "eske 50",
    ammo: {
      caliber: ".17 HMR",
      projectileType: "SP",
      v0: 777,
      bc: 0.12,
      bcModel: "G1",
      damageFactor: 0.8,
      maxAchievableMoa: 1.0,
    },
  },
  {
    id: "ammo-norma-308-fmj",
    category: "ammo",
    brand: "Norma",
    name: "FMJ Training 9,7g",
    priceNok: 480,
    unitLabel: "eske 50",
    ammo: {
      caliber: ".308 Win",
      projectileType: "FMJ",
      v0: 820,
      bc: 0.4,
      bcModel: "G1",
      damageFactor: 0.24,
      maxAchievableMoa: 1.0,
    },
  },
  {
    id: "ammo-lapua-308-scenar",
    category: "ammo",
    brand: "Lapua",
    name: "Scenar 167gr OTM",
    priceNok: 890,
    unitLabel: "eske 20",
    ammo: {
      caliber: ".308 Win",
      projectileType: "OTM",
      v0: 800,
      bc: 0.446,
      bcModel: "G1",
      damageFactor: 0.18,
      maxAchievableMoa: 0.25,
    },
  },
  {
    id: "ammo-federal-308-goldmedal",
    category: "ammo",
    brand: "Federal",
    name: "Gold Medal Sierra MatchKing 168gr",
    priceNok: 820,
    unitLabel: "eske 20",
    ammo: {
      caliber: ".308 Win",
      projectileType: "OTM",
      v0: 810,
      bc: 0.462,
      bcModel: "G1",
      damageFactor: 0.19,
      maxAchievableMoa: 0.3,
    },
  },
  {
    id: "ammo-sako-308-hammerhead",
    category: "ammo",
    brand: "Sako",
    name: "Hammerhead 180gr",
    priceNok: 680,
    unitLabel: "eske 20",
    ammo: {
      caliber: ".308 Win",
      projectileType: "SP",
      v0: 790,
      bc: 0.36,
      bcModel: "G1",
      damageFactor: 0.78,
      maxAchievableMoa: 0.65,
    },
  },
  {
    id: "ammo-norma-308-orca",
    category: "ammo",
    brand: "Norma",
    name: "Oryx 11,7g / 180gr",
    priceNok: 720,
    unitLabel: "eske 20",
    ammo: {
      caliber: ".308 Win",
      projectileType: "SP",
      v0: 780,
      bc: 0.36,
      bcModel: "G1",
      damageFactor: 0.74,
      maxAchievableMoa: 0.7,
    },
  },
  {
    id: "ammo-norma-3006-alaska",
    category: "ammo",
    brand: "Norma",
    name: "Alaska 11,7g / 180gr",
    priceNok: 740,
    unitLabel: "eske 20",
    ammo: {
      caliber: ".30-06",
      projectileType: "SP",
      v0: 820,
      bc: 0.33,
      bcModel: "G1",
      damageFactor: 0.76,
      maxAchievableMoa: 0.8,
    },
  },
  {
    id: "ammo-sako-3006-gamehead",
    category: "ammo",
    brand: "Sako",
    name: "Gamehead 180gr",
    priceNok: 690,
    unitLabel: "eske 20",
    ammo: {
      caliber: ".30-06",
      projectileType: "SP",
      v0: 830,
      bc: 0.35,
      bcModel: "G1",
      damageFactor: 0.65,
      maxAchievableMoa: 0.55,
    },
  },
  {
    id: "ammo-remington-3006-corelokt",
    category: "ammo",
    brand: "Remington",
    name: "Core-Lokt 150gr",
    priceNok: 590,
    unitLabel: "eske 20",
    ammo: {
      caliber: ".30-06",
      projectileType: "SP",
      v0: 890,
      bc: 0.314,
      bcModel: "G1",
      damageFactor: 0.8,
      maxAchievableMoa: 1.1,
    },
  },
  {
    id: "ammo-biltema-22lr-bulk",
    category: "ammo",
    brand: "Biltema",
    name: "Bulk .22 LR",
    priceNok: 99,
    unitLabel: "eske 100",
    note: "Høyt volum, høyt håp, variabel treffpunkt.",
    ammo: {
      caliber: ".22 LR",
      projectileType: "FMJ",
      v0: 340,
      bc: 0.11,
      bcModel: "G1",
      damageFactor: 0.4,
      maxAchievableMoa: 1.8,
    },
  },
  {
    id: "ammo-jula-308-fmj",
    category: "ammo",
    brand: "Jula",
    name: "FMJ .308 trening",
    priceNok: 349,
    unitLabel: "eske 50",
    ammo: {
      caliber: ".308 Win",
      projectileType: "FMJ",
      v0: 800,
      bc: 0.38,
      bcModel: "G1",
      damageFactor: 0.25,
      maxAchievableMoa: 1.5,
    },
  },

  // --- CB Customs home loads (XXL: not for sale — order at CB Customs) ---
  {
    id: "ammo-cb-homeload-65x55",
    category: "ammo",
    brand: "CB Customs",
    name: "Home Load 6,5×55",
    priceNok: 100,
    unitLabel: "skudd 1",
    note: "Spesiallager for presisjon. Kun hos CB Customs.",
    ammo: {
      caliber: "6,5×55",
      projectileType: "OTM",
      v0: 805,
      bc: 0.489,
      bcModel: "G1",
      damageFactor: 0.2,
      maxAchievableMoa: 0.2,
      v0SigmaMps: 3,
    },
  },
  {
    id: "ammo-cb-homeload-65cm",
    category: "ammo",
    brand: "CB Customs",
    name: "Home Load 6,5 Creedmoor",
    priceNok: 100,
    unitLabel: "skudd 1",
    note: "Spesiallager for presisjon. Kun hos CB Customs.",
    ammo: {
      caliber: "6,5 Creedmoor",
      projectileType: "OTM",
      v0: 830,
      bc: 0.508,
      bcModel: "G1",
      damageFactor: 0.2,
      maxAchievableMoa: 0.2,
      v0SigmaMps: 3,
    },
  },
  {
    id: "ammo-cb-homeload-308",
    category: "ammo",
    brand: "CB Customs",
    name: "Home Load .308 Win",
    priceNok: 100,
    unitLabel: "skudd 1",
    note: "Spesiallager for presisjon. Kun hos CB Customs.",
    ammo: {
      caliber: ".308 Win",
      projectileType: "OTM",
      v0: 820,
      bc: 0.475,
      bcModel: "G1",
      damageFactor: 0.22,
      maxAchievableMoa: 0.2,
      v0SigmaMps: 3,
    },
  },
  {
    id: "ammo-cb-homeload-3006",
    category: "ammo",
    brand: "CB Customs",
    name: "Home Load .30-06",
    priceNok: 100,
    unitLabel: "skudd 1",
    note: "Spesiallager for presisjon. Kun hos CB Customs.",
    ammo: {
      caliber: ".30-06",
      projectileType: "OTM",
      v0: 850,
      bc: 0.45,
      bcModel: "G1",
      damageFactor: 0.22,
      maxAchievableMoa: 0.2,
      v0SigmaMps: 3.5,
    },
  },
  {
    id: "ammo-cb-homeload-223",
    category: "ammo",
    brand: "CB Customs",
    name: "Home Load .223 Rem",
    priceNok: 100,
    unitLabel: "skudd 1",
    note: "Spesiallager for presisjon. Kun hos CB Customs.",
    ammo: {
      caliber: ".223 Rem",
      projectileType: "OTM",
      v0: 900,
      bc: 0.35,
      bcModel: "G1",
      damageFactor: 0.2,
      maxAchievableMoa: 0.25,
      v0SigmaMps: 3.5,
    },
  },
  {
    id: "ammo-cb-homeload-22lr",
    category: "ammo",
    brand: "CB Customs",
    name: "Home Load .22 LR",
    priceNok: 100,
    unitLabel: "skudd 1",
    note: "Spesiallager for presisjon. Kun hos CB Customs.",
    ammo: {
      caliber: ".22 LR",
      projectileType: "FMJ",
      v0: 330,
      bc: 0.13,
      bcModel: "G1",
      damageFactor: 0.35,
      maxAchievableMoa: 0.35,
      v0SigmaMps: 4,
    },
  },

  // --- Ballistics (weather / solvers) ---
  {
    id: "misc-kestrel-5700-elite",
    category: "ballistics",
    brand: "Kestrel",
    name: "5700 Elite (Applied Ballistics)",
    priceNok: 8990,
    note: "Vær + vind + Applied Ballistics. Gir fasit for elev og windage.",
    ballistics: {
      measuresCrosswind: true,
      windErrorPercent: 3,
      tempErrorC: 0.5,
      readingAccuracy: 10,
      solver: "Applied Ballistics",
    },
  },
  {
    id: "misc-kestrel-5500",
    category: "ballistics",
    brand: "Kestrel",
    name: "5500 Weather Meter",
    priceNok: 4990,
    soldOut: true,
    note: "Vær/vind uten full AB-elite. — Sold out",
    ballistics: {
      measuresCrosswind: true,
      windErrorPercent: 5,
      tempErrorC: 0.8,
      readingAccuracy: 8,
    },
  },
  {
    id: "misc-vortex-ace-ballistic",
    category: "ballistics",
    brand: "Vortex",
    name: "ACE Ballistic Weather Meter",
    priceNok: 7490,
    soldOut: true,
    note: "GeoBallistics on-board — Kestrel-alternativ. — Sold out",
    ballistics: {
      measuresCrosswind: true,
      windErrorPercent: 4,
      tempErrorC: 0.6,
      readingAccuracy: 9,
      solver: "GeoBallistics",
    },
  },
  {
    id: "misc-skywatch-bl",
    category: "ballistics",
    brand: "Skywatch",
    name: "BL / Atmos",
    priceNok: 2490,
    soldOut: true,
    note: "Kompakt vær/vind til telefon. — Sold out",
    ballistics: {
      measuresCrosswind: true,
      windErrorPercent: 8,
      tempErrorC: 1.2,
      readingAccuracy: 6,
    },
  },
  {
    id: "misc-weatherflow-weathermeter",
    category: "ballistics",
    brand: "WeatherFlow",
    name: "WEATHERmeter",
    priceNok: 1290,
    soldOut: true,
    note: "Plug-in anemometer til mobilen. — Sold out",
    ballistics: {
      measuresCrosswind: true,
      windErrorPercent: 10,
      tempErrorC: 1.5,
      readingAccuracy: 5,
    },
  },
  {
    id: "misc-clas-ohlson-anemometer",
    category: "ballistics",
    brand: "Clas Ohlson",
    name: "Digital vindmåler",
    priceNok: 399,
    soldOut: true,
    note: "Budget vind. God nok til å skjønne at det blåser. — Sold out",
    ballistics: {
      measuresCrosswind: true,
      windErrorPercent: 16,
      tempErrorC: 2.5,
      readingAccuracy: 3,
    },
  },
  {
    id: "misc-garmin-foretrex-801",
    category: "ballistics",
    brand: "Garmin",
    name: "Foretrex 801",
    priceNok: 4490,
    soldOut: true,
    note: "Håndledd-GPS; ballistikk via app/økosystem. — Sold out",
    ballistics: {
      measuresCrosswind: false,
      windErrorPercent: 18,
      tempErrorC: 2,
      readingAccuracy: 5,
      solver: "App / forecast",
    },
  },

  // --- Backpacks ---
  {
    id: "misc-vorn-deer-42",
    category: "backpack",
    brand: "Vorn",
    name: "Deer 42L",
    priceNok: 3495,
    note: "QRR — rifla klar på ryggen. Reduserer rifle-faffe og vektstraff.",
    carry: {
      carryComfort: 8,
      quickRelease: 9,
      opticsAccess: 3,
    },
  },
  {
    id: "misc-eberlestock-gunrunner-h2",
    category: "backpack",
    brand: "Eberlestock",
    name: "H2 Gunrunner",
    priceNok: 3199,
    note: "Lett scabbard-pack — rask rifle, litt mindre last-effektivitet enn Vorn.",
    carry: {
      carryComfort: 7,
      quickRelease: 8,
      opticsAccess: 4,
    },
  },
  {
    id: "misc-eberlestock-x1-euro",
    category: "backpack",
    brand: "Eberlestock",
    name: "X1 Euro II",
    priceNok: 4490,
    note: "Større pack-system — bærer tungt, rifle litt tregere enn Gunrunner.",
    carry: {
      carryComfort: 9,
      quickRelease: 7,
      opticsAccess: 3,
    },
  },
  {
    id: "pack-fjellsekk-budget",
    category: "backpack",
    brand: "Biltema",
    name: "Fjellsekk 40L",
    priceNok: 399,
    note: "Bærer greit. Rifla i stropper = mye faffe.",
    carry: {
      carryComfort: 3,
      quickRelease: 3,
      opticsAccess: 2,
    },
  },
  {
    id: "pack-jula-daypack",
    category: "backpack",
    brand: "Jula",
    name: "Daypack 25L",
    priceNok: 249,
    carry: {
      carryComfort: 2,
      quickRelease: 2,
      opticsAccess: 1,
    },
  },

  // --- Chestrigs (LRF / optics access) ---
  {
    id: "chest-cds-binocular-harness",
    category: "chestrig",
    brand: "Cotton Carrier",
    name: "Binocular / LRF harness",
    priceNok: 1890,
    note: "Kikkert/LRF på brystet — dramatisk mindre observasjons-faffe.",
    carry: {
      carryComfort: 4,
      quickRelease: 3,
      opticsAccess: 8,
    },
  },
  {
    id: "chest-badlands-bino-harness",
    category: "chestrig",
    brand: "Badlands",
    name: "Bino Case / Harness",
    priceNok: 2490,
    note: "Solid LRF/bino-bære. Rask observasjon, litt vektstøtte.",
    carry: {
      carryComfort: 5,
      quickRelease: 3,
      opticsAccess: 9,
    },
  },
  {
    id: "chest-marsupial-bino",
    category: "chestrig",
    brand: "Marsupial Gear",
    name: "Binocular Pack",
    priceNok: 2190,
    carry: {
      carryComfort: 5,
      quickRelease: 3,
      opticsAccess: 9,
    },
  },
  {
    id: "chest-kuiu-pro",
    category: "chestrig",
    brand: "KUIU",
    name: "Pro Bino Harness",
    priceNok: 2790,
    note: "Premium harness — rask tilgang, bedre lastfordeling.",
    carry: {
      carryComfort: 6,
      quickRelease: 4,
      opticsAccess: 9,
    },
  },
  {
    id: "chest-sitka-mountain",
    category: "chestrig",
    brand: "Sitka",
    name: "Mountain Optics Harness",
    priceNok: 2990,
    carry: {
      carryComfort: 6,
      quickRelease: 4,
      opticsAccess: 10,
    },
  },
  {
    id: "chest-biltema-strap",
    category: "chestrig",
    brand: "Biltema",
    name: "Kikkertsele / bryststropp",
    priceNok: 149,
    note: "Bedre enn lomma. Fortsatt litt faffe.",
    carry: {
      carryComfort: 2,
      quickRelease: 3,
      opticsAccess: 4,
    },
  },
  {
    id: "chest-jula-neck",
    category: "chestrig",
    brand: "Jula",
    name: "Nakkerem + pouch",
    priceNok: 99,
    carry: {
      carryComfort: 2,
      quickRelease: 3,
      opticsAccess: 3,
    },
  },

  // --- Bipods / Tofot ---
  {
    id: "bipod-game-on-softgun",
    category: "bipod",
    brand: "Game-On",
    name: "Softgun Tofot (plast)",
    priceNok: 249,
    note: "Airsoft-hylla. Fleksibel, skranglete — bedre enn ingenting på 50 m.",
    bipod: { weaponCalm: 2, deploySpeed: 5, tracking: 1 },
  },
  {
    id: "bipod-jula-budget",
    category: "bipod",
    brand: "Jula",
    name: "Budget tofot",
    priceNok: 199,
    note: "Løs picatinny-greie. Wobble inkludert.",
    bipod: { weaponCalm: 2, deploySpeed: 4, tracking: 1 },
  },
  {
    id: "bipod-utg-shooter",
    category: "bipod",
    brand: "UTG",
    name: "Shooter Style Bipod",
    priceNok: 690,
    note: "Billig aluminium. Funker til nulling på 100 m.",
    bipod: { weaponCalm: 3, deploySpeed: 5, tracking: 2 },
  },
  {
    id: "bipod-caldwell-xla",
    category: "bipod",
    brand: "Caldwell",
    name: "XLA Bipod",
    priceNok: 1290,
    note: "Lett polymer mid-budget. Jaktvennlig vekt.",
    bipod: { weaponCalm: 4, deploySpeed: 6, tracking: 3 },
  },
  {
    id: "bipod-harris-s-brm",
    category: "bipod",
    brand: "Harris",
    name: "S-BRM 6-9\"",
    priceNok: 2490,
    note: "Klassisk stål-Harris. Tøff, litt tung, pålitelig.",
    bipod: { weaponCalm: 6, deploySpeed: 5, tracking: 4 },
  },
  {
    id: "bipod-magpul-bipod",
    category: "bipod",
    brand: "Magpul",
    name: "Bipod (M-LOK / Pic)",
    priceNok: 3290,
    note: "Polymer mid. Rask fold, grei stabilitet til jakt.",
    bipod: { weaponCalm: 6, deploySpeed: 7, tracking: 5 },
  },
  {
    id: "bipod-atlas-bt65",
    category: "bipod",
    brand: "B&T Atlas",
    name: "BT65 CAL / PSR-style",
    priceNok: 5990,
    note: "Pan/cant-konge i mellomklassen. PRS-legende.",
    bipod: { weaponCalm: 8, deploySpeed: 7, tracking: 9 },
  },
  {
    id: "bipod-spartan-javelin",
    category: "bipod",
    brand: "Spartan Precision",
    name: "Javelin Carbon",
    priceNok: 5490,
    note: "Lett carbon jakttofot. Rask av/på — mindre PRS-track.",
    bipod: { weaponCalm: 7, deploySpeed: 9, tracking: 6 },
  },
  {
    id: "bipod-accu-tac-br4",
    category: "bipod",
    brand: "Accu-Tac",
    name: "BR-4 G2",
    priceNok: 6990,
    note: "Solid mid-PRS. Tung nok til å dempe, ikke full FC.",
    bipod: { weaponCalm: 8, deploySpeed: 6, tracking: 8 },
  },
  {
    id: "bipod-mdt-ckye-pod",
    category: "bipod",
    brand: "MDT",
    name: "CKYE-POD Single Pull",
    priceNok: 8990,
    note: "PRS-standard. Rask høyde, sterk tracking.",
    bipod: { weaponCalm: 9, deploySpeed: 8, tracking: 9 },
  },
  {
    id: "bipod-accu-tac-fc5",
    category: "bipod",
    brand: "Accu-Tac",
    name: "FC-5 G2 (tung PRS)",
    priceNok: 9990,
    note: "Tung stål-PRS. Våpenet ligger som støpt — koster gram i sekken.",
    bipod: { weaponCalm: 10, deploySpeed: 5, tracking: 9 },
  },
  {
    id: "bipod-phoenix-precision",
    category: "bipod",
    brand: "Phoenix Precision",
    name: "Carbon PRS Pod",
    priceNok: 11990,
    note: "Dyrt carbon: høy stabilitet uten full Accu-Tac-vekt.",
    bipod: { weaponCalm: 9, deploySpeed: 7, tracking: 9 },
  },
  {
    id: "bipod-trs-really-right",
    category: "bipod",
    brand: "Really Right Stuff",
    name: "Anvil-19 / RRS-style",
    priceNok: 13990,
    note: "Topphylla PRS/jakt-hybrid. Pan, cant, stivhet — og pris.",
    bipod: { weaponCalm: 10, deploySpeed: 7, tracking: 10 },
  },

  // --- Skis / Snowshoes ---
  {
    id: "ski-asnes-kongsvoll",
    category: "skis",
    brand: "Åsnes",
    name: "Kongsvoll",
    priceNok: 4490,
    note: "Klassisk fjellski — balansert fart og flyt.",
    ski: { maxSpeed: 7, flowPerKg: 7, widthMm: 65 },
  },
  {
    id: "ski-asnes-combat",
    category: "skis",
    brand: "Åsnes",
    name: "Combat",
    priceNok: 4990,
    note: "Bredere militær-/jaktprofil. Tåler sekk bedre i snø.",
    ski: { maxSpeed: 6, flowPerKg: 8, widthMm: 80 },
  },
  {
    id: "ski-natoplank",
    category: "skis",
    brand: "NATO",
    name: "Natoplank",
    priceNok: 1890,
    note: "Tunge, brede. Treg på hardt føre — konge i dyp snø med tung sekk.",
    ski: { maxSpeed: 4, flowPerKg: 9, widthMm: 100 },
  },
  {
    id: "ski-sgn-togga",
    category: "skis",
    brand: "SGN",
    name: "Togga",
    priceNok: 5990,
    note: "Moderne jakt-/fjellski. Bred 120 mm — sterk i dyp snø med sekk.",
    ski: { maxSpeed: 7, flowPerKg: 8, widthMm: 120 },
  },
  {
    id: "ski-dps-judas",
    category: "skis",
    brand: "DPS",
    name: "Judas",
    priceNok: 7490,
    note: "Bred powder-ski. Mye flyt per kilo i dyp snø.",
    ski: { maxSpeed: 5, flowPerKg: 9, widthMm: 110 },
  },
  {
    id: "ski-joggepinner",
    category: "skis",
    brand: "Budget",
    name: "Joggepinner",
    priceNok: 990,
    note: "Smale og lette. Raskt på hardt føre — synker med tung sekk i dyp snø.",
    ski: { maxSpeed: 9, flowPerKg: 3, widthMm: 45 },
  },
  {
    id: "ski-jobbepinner-feller",
    category: "skis",
    brand: "Budget",
    name: "Jobbepinner med feller",
    priceNok: 1490,
    note: "Arbeidsski med feller. Mindre toppfart, bedre oppover og under last.",
    ski: { maxSpeed: 5, flowPerKg: 6, widthMm: 55 },
  },

  // --- Food & cook ---
  // Real needs stove+gas for stamina. Ready food works cold.
  {
    id: "food-real-turmat",
    category: "food",
    brand: "Real Turmat",
    name: "Frysetørket middag (1 porsjon)",
    priceNok: 120,
    note: "120 kr!!!! Sykt. Body +40% · Mind +30% · 15 min — krever kokt vann.",
    food: {
      kind: "meal",
      huntTrips: 1,
      staminaGain: 9,
      bodyGain: 0.4,
      mindGain: 0.3,
      minutes: 15,
      requiresBoil: true,
    },
  },
  {
    id: "food-msr-pocketrocket",
    category: "food",
    brand: "MSR",
    name: "PocketRocket 2",
    priceNok: 899,
    note: "Lett brenner. Uten gassboks koker du ingenting.",
    food: {
      kind: "stove",
      huntTrips: 999,
      staminaGain: 0,
      bodyGain: 0,
      mindGain: 0,
      minutes: 0,
      requiresBoil: false,
    },
  },
  {
    id: "food-msr-isopro-230",
    category: "food",
    brand: "MSR",
    name: "IsoPro gassboks 230 g",
    priceNok: 149,
    note: "Varer ca. 10 jaktturer med PocketRocket (kok til Real).",
    food: {
      kind: "fuel",
      huntTrips: 10,
      staminaGain: 0,
      bodyGain: 0,
      mindGain: 0,
      minutes: 0,
      requiresBoil: false,
    },
  },
  {
    id: "food-rema-brod",
    category: "food",
    brand: "Rema 1000",
    name: "Brød (loff)",
    priceNok: 39,
    note: "Kald mat. Body +15% · Mind +8% · 5 min. Varer 2 jaktturer.",
    food: {
      kind: "ready",
      huntTrips: 2,
      staminaGain: 4,
      bodyGain: 0.15,
      mindGain: 0.08,
      minutes: 5,
      requiresBoil: false,
    },
  },
  {
    id: "food-polarbrod-ost-skinke",
    category: "food",
    brand: "Polarbrød",
    name: "Med ost og skinke",
    priceNok: 200,
    note: "Body +20% · Mind +12% · 5 min. Varer 2 jaktturer.",
    food: {
      kind: "ready",
      huntTrips: 2,
      staminaGain: 5,
      bodyGain: 0.2,
      mindGain: 0.12,
      minutes: 5,
      requiresBoil: false,
    },
  },
  {
    id: "food-circlek-baguette",
    category: "food",
    brand: "Circle K",
    name: "Baguette",
    priceNok: 100,
    note: "Body +12% · Mind +8% · 5 min. Varer 1 jakttur.",
    food: {
      kind: "ready",
      huntTrips: 1,
      staminaGain: 3,
      bodyGain: 0.12,
      mindGain: 0.08,
      minutes: 5,
      requiresBoil: false,
    },
  },
  {
    id: "food-boller-5pk",
    category: "food",
    brand: "Bakeriet",
    name: "5-pk boller",
    priceNok: 79,
    note: "Body +10% · Mind +15% · 5 min. Sukker-rush.",
    food: {
      kind: "ready",
      huntTrips: 1,
      staminaGain: 3,
      bodyGain: 0.1,
      mindGain: 0.15,
      minutes: 5,
      requiresBoil: false,
    },
  },
  {
    id: "food-dronning-kokesjokolade",
    category: "food",
    brand: "Dronning",
    name: "Kokesjokolade",
    priceNok: 45,
    note: "Mind +20% · Body +5% · 5 min. Smelter i sekken om du ikke passer på.",
    food: {
      kind: "ready",
      huntTrips: 1,
      staminaGain: 4,
      bodyGain: 0.05,
      mindGain: 0.2,
      minutes: 5,
      requiresBoil: false,
    },
  },

  // --- Misc kult kit (rest) ---
  // Every misc item: weightGrams + misc.enduranceGrams (felt ≈ weight − endurance).
  {
    id: "misc-suunto-a-10",
    category: "misc",
    brand: "Suunto",
    name: "A-10 Speilkompass",
    priceNok: 0,
    note: "Standard i kit (gratis) — retning i spotting. Billig og nødvendig for søk/skuddpar uten kamera.",
    misc: { enduranceGrams: 0 },
  },
  {
    id: "misc-sittpute-biltema",
    category: "misc",
    brand: "Biltema",
    name: "Sittpute / sitteunderlag",
    priceNok: 79,
    note: "Tørr rumpe = mer tålmodighet på post.",
    misc: { enduranceGrams: 400 },
  },
  {
    id: "misc-thermos-jula",
    category: "misc",
    brand: "Jula",
    name: "Termos 1L",
    priceNok: 149,
    note: "Kaffe er også kit. Weight + Endurance-offset.",
    misc: { enduranceGrams: 2000 },
  },
  {
    id: "misc-nightcore-nu21",
    category: "misc",
    brand: "Nitecore",
    name: "NU21",
    priceNok: 349,
    note: "Hodelykt — gå tilbake til bilen etter mørkets frembrudd. Uten denne: camp ute.",
    misc: { enduranceGrams: 0, isHeadlamp: true },
  },
  {
    id: "misc-nightcore-hc60",
    category: "misc",
    brand: "Nitecore",
    name: "HC60",
    priceNok: 1099,
    note: "Sterk hodelykt m/USB-lading. Samme nattgåing, bedre lys og litt mindre vekt i sekken.",
    misc: { enduranceGrams: 150, isHeadlamp: true },
  },
  {
    id: "misc-triggercam",
    category: "misc",
    brand: "Triggercam",
    name: "Triggercam TC-2",
    priceNok: 9690,
    note: "After-action replay: se nøyaktig hvor skuddet traff (og bommet). Strammer også ettersøk-retning kraftig.",
    misc: { enduranceGrams: 0 },
  },
  {
    id: "misc-hunt-camcorder",
    category: "misc",
    brand: "Sony",
    name: "FDR-AX43 (jakt-oppsett)",
    priceNok: 12490,
    note: "Stativ-camcorder mot standplass. Gir retning + landingsavstand fra der fuglen satt — men tar tid å sette opp (fuglen blir nervøs).",
    misc: { enduranceGrams: 0, isCamcorder: true },
  },
  {
    id: "misc-garmin-xero-c1-pro",
    category: "misc",
    brand: "Garmin",
    name: "Xero C1 Pro",
    priceNok: 5499,
    note:
      "Doppler-kronograf — måler reell muzzle velocity. I kit på skytebane: shotlog logger v0 + temperatur per serie. På jakt: Sett opp Chrono (+5 % nervøsitet) før skudd — da logges v0 + temperatur.",
    misc: { enduranceGrams: 0, isChronograph: true },
  },
  {
    id: "misc-fx-true-ballistic",
    category: "misc",
    brand: "FX",
    name: "True Ballistic Chronograph",
    priceNok: 11990,
    note:
      "Radar-kronograf — måler reell hastighet (og hastighet langs banen / BC via app). " +
      "Premium kult kit; funksjon kobles inn senere.",
    misc: { enduranceGrams: 0, isChronograph: true },
  },

  // --- Camouflage ---
  // birdSpotSnow / birdSpotNoSnow: lower = harder for birds to spot in that condition.
  {
    id: "camo-kuiu-valo",
    category: "camo",
    brand: "KUIU",
    name: "Valo (jaktsett)",
    priceNok: 8990,
    note: "Lavkontrast «mountain/open» — dødt gress, lyng, åpent terreng.",
    camo: {
      birdSpotSnow: 0.7,
      birdSpotNoSnow: 0.26,
      bestTerrains: ["open_mountain", "bog_heath", "autumn_forest"],
      slot: "suit",
      terrainSpeed: 8,
      stamina: 8,
    },
  },
  {
    id: "camo-kuiu-vias",
    category: "camo",
    brand: "KUIU",
    name: "Vias (jaktsett)",
    priceNok: 8990,
    note: "Høykontrast alpine — ur, stein, over tregrensa.",
    camo: {
      birdSpotSnow: 0.68,
      birdSpotNoSnow: 0.28,
      bestTerrains: ["open_mountain"],
      slot: "suit",
      terrainSpeed: 8,
      stamina: 8,
    },
  },
  {
    id: "camo-kuiu-verde",
    category: "camo",
    brand: "KUIU",
    name: "Verde (jaktsett)",
    priceNok: 8990,
    note: "Vegetasjon / skog / grønt–brunt.",
    camo: {
      birdSpotSnow: 0.74,
      birdSpotNoSnow: 0.24,
      bestTerrains: ["pine_forest", "autumn_forest"],
      slot: "suit",
      terrainSpeed: 8,
      stamina: 8,
    },
  },
  {
    id: "camo-sitka-subalpine",
    category: "camo",
    brand: "Sitka",
    name: "OPTIFADE Subalpine",
    priceNok: 10990,
    note: "Designet mot dyrs syn — skog/vegetasjon på bakkenivå.",
    camo: {
      birdSpotSnow: 0.72,
      birdSpotNoSnow: 0.22,
      bestTerrains: ["pine_forest", "autumn_forest"],
      slot: "suit",
      terrainSpeed: 8,
      stamina: 8,
    },
  },
  {
    id: "camo-sitka-open-country",
    category: "camo",
    brand: "Sitka",
    name: "OPTIFADE Open Country",
    priceNok: 10990,
    note: "Åpent fjell / lang hold — bryter silhuett på avstand.",
    camo: {
      birdSpotSnow: 0.7,
      birdSpotNoSnow: 0.24,
      bestTerrains: ["open_mountain", "bog_heath"],
      slot: "suit",
      terrainSpeed: 8,
      stamina: 8,
    },
  },
  {
    id: "camo-finnish-m05-snow",
    category: "camo",
    brand: "Varusteleka / M05",
    name: "Finnish M05 Snow Camo",
    priceNok: 3490,
    note: "Finsk snøkamo (Varusteleka) — ekstremt bra i snø.",
    camo: {
      birdSpotSnow: 0.1,
      birdSpotNoSnow: 0.84,
      bestTerrains: ["snow", "snow_broken"],
      slot: "suit",
      terrainSpeed: 6,
      stamina: 6,
    },
  },
  {
    id: "camo-finnish-m05-winter",
    category: "camo",
    brand: "Varusteleka / M05",
    name: "Finnish M05 Winter Camo",
    priceNok: 3790,
    note: "M05 winter — snø med mer brudd (skog/stein i hvitt).",
    camo: {
      birdSpotSnow: 0.12,
      birdSpotNoSnow: 0.78,
      bestTerrains: ["snow_broken", "snow", "pine_forest"],
      slot: "suit",
      terrainSpeed: 6,
      stamina: 6,
    },
  },
  {
    id: "camo-norwegian-snow",
    category: "camo",
    brand: "Forsvaret / NO",
    name: "Norwegian Snow Camo (ny)",
    priceNok: 0,
    note: "Unobtainable — moderne norsk snøkamo. Finnes i spillet, aldri til salgs i XXL.",
    camo: {
      birdSpotSnow: 0.08,
      birdSpotNoSnow: 0.85,
      bestTerrains: ["snow", "snow_broken"],
      availableInShop: false,
      slot: "suit",
      terrainSpeed: 9,
      stamina: 9,
    },
  },
  {
    id: "camo-norwegian-vintage-snow",
    category: "camo",
    brand: "Norsk surplus",
    name: "Norwegian Vintage Snow Camo",
    priceNok: 690,
    note: "Billig hvitt overtrekk. Effektivt i snø, svakere brudd enn moderne mønster.",
    camo: {
      birdSpotSnow: 0.18,
      birdSpotNoSnow: 0.88,
      bestTerrains: ["snow"],
      slot: "suit",
      terrainSpeed: 4,
      stamina: 4,
    },
  },
  {
    id: "camo-harkila-pro-hunter",
    category: "camo",
    brand: "Härkila",
    name: "Pro Hunter / Mountain",
    priceNok: 7990,
    note: "Nordisk jaktkamo — høstskog og fjellskog.",
    camo: {
      birdSpotSnow: 0.72,
      birdSpotNoSnow: 0.27,
      bestTerrains: ["autumn_forest", "pine_forest", "open_mountain"],
      slot: "suit",
      terrainSpeed: 7,
      stamina: 7,
    },
  },
  {
    id: "camo-pinewood-lappland",
    category: "camo",
    brand: "Pinewood",
    name: "Lappland / Hunter",
    priceNok: 3490,
    note: "Vanlig norsk/svensk jaktkamo for høst.",
    camo: {
      birdSpotSnow: 0.74,
      birdSpotNoSnow: 0.3,
      bestTerrains: ["autumn_forest", "pine_forest", "bog_heath"],
      slot: "suit",
      terrainSpeed: 6,
      stamina: 6,
    },
  },
  {
    id: "camo-m05-woodland",
    category: "camo",
    brand: "Varusteleka / M05",
    name: "Finnish M05 Woodland",
    priceNok: 2890,
    note: "Klassisk finsk skogkamo — grønt/brunt, ikke snø.",
    camo: {
      birdSpotSnow: 0.76,
      birdSpotNoSnow: 0.26,
      bestTerrains: ["pine_forest", "autumn_forest"],
      slot: "suit",
      terrainSpeed: 6,
      stamina: 6,
    },
  },
  {
    id: "camo-nordic-autumn-brush",
    category: "camo",
    brand: "Nordic Hunt",
    name: "Autumn Brush",
    priceNok: 2490,
    note: "Generell norsk høstkamo — lyng, bjørk, barskogskant.",
    camo: {
      birdSpotSnow: 0.75,
      birdSpotNoSnow: 0.29,
      bestTerrains: ["autumn_forest", "bog_heath", "pine_forest"],
      slot: "suit",
      terrainSpeed: 6,
      stamina: 6,
    },
  },
  {
    id: "camo-biltema-leaf",
    category: "camo",
    brand: "Biltema",
    name: "Leaf Camo sett",
    priceNok: 599,
    note: "Budget. Fungerer litt. Fuglene er ikke imponert.",
    camo: {
      birdSpotSnow: 0.78,
      birdSpotNoSnow: 0.42,
      bestTerrains: ["autumn_forest", "general"],
      slot: "suit",
      terrainSpeed: 4,
      stamina: 4,
    },
  },
  {
    id: "camo-jula-forest",
    category: "camo",
    brand: "Jula",
    name: "Forest Camo overall",
    priceNok: 499,
    camo: {
      birdSpotSnow: 0.8,
      birdSpotNoSnow: 0.45,
      bestTerrains: ["pine_forest", "general"],
      slot: "suit",
      terrainSpeed: 4,
      stamina: 4,
    },
  },

  // --- Camo apparel: buff / lue / hansker / boots / skistøvler ---
  {
    id: "camo-buff-mesh-multicam",
    category: "camo",
    brand: "Buff",
    name: "Mesh Multicam",
    priceNok: 300,
    note: "Ekte Buff mesh — ansikt/hals. Bedre enn Temu.",
    camo: {
      birdSpotSnow: 0.55,
      birdSpotNoSnow: 0.34,
      bestTerrains: ["general", "pine_forest", "open_mountain"],
      slot: "buff",
      terrainSpeed: 4,
      stamina: 4,
    },
  },
  {
    id: "camo-buff-mesh-snow-temu",
    category: "camo",
    brand: "Temu",
    name: "Mesh Buff Snow",
    priceNok: 50,
    note: "50 kr. Synker litt når det blir vått.",
    camo: {
      birdSpotSnow: 0.42,
      birdSpotNoSnow: 0.78,
      bestTerrains: ["snow"],
      slot: "buff",
      terrainSpeed: 2,
      stamina: 2,
    },
  },
  {
    id: "camo-buff-mesh-multicam-temu",
    category: "camo",
    brand: "Temu",
    name: "Mesh Buff Multicam",
    priceNok: 50,
    note: "Billig kopi. Lukter plast første uke.",
    camo: {
      birdSpotSnow: 0.72,
      birdSpotNoSnow: 0.48,
      bestTerrains: ["general"],
      slot: "buff",
      terrainSpeed: 2,
      stamina: 2,
    },
  },
  {
    id: "camo-buff-snow-realtree",
    category: "camo",
    brand: "Realtree",
    name: "Buff Snow",
    priceNok: 150,
    note: "Snømønster rundt halsen — hjelper i snø.",
    camo: {
      birdSpotSnow: 0.28,
      birdSpotNoSnow: 0.72,
      bestTerrains: ["snow", "snow_broken"],
      slot: "buff",
      terrainSpeed: 3,
      stamina: 3,
    },
  },
  {
    id: "camo-buff-autumn-realtree",
    category: "camo",
    brand: "Realtree",
    name: "Buff Autumn",
    priceNok: 150,
    note: "Høstmønster — bra uten snø.",
    camo: {
      birdSpotSnow: 0.72,
      birdSpotNoSnow: 0.3,
      bestTerrains: ["autumn_forest", "pine_forest"],
      slot: "buff",
      terrainSpeed: 3,
      stamina: 3,
    },
  },
  {
    id: "camo-beanie-snow-swedteam",
    category: "camo",
    brand: "Swedteam",
    name: "Beanie / lue Snow",
    priceNok: 200,
    note: "Snølue — hodekontur mot himmel/snø.",
    camo: {
      birdSpotSnow: 0.32,
      birdSpotNoSnow: 0.68,
      bestTerrains: ["snow"],
      slot: "beanie",
      terrainSpeed: 4,
      stamina: 5,
    },
  },
  {
    id: "camo-beanie-forest-swedteam",
    category: "camo",
    brand: "Swedteam",
    name: "Beanie / lue Forest",
    priceNok: 200,
    note: "Skoglue — mindre silhuett i barskog.",
    camo: {
      birdSpotSnow: 0.7,
      birdSpotNoSnow: 0.32,
      bestTerrains: ["pine_forest", "autumn_forest"],
      slot: "beanie",
      terrainSpeed: 4,
      stamina: 5,
    },
  },
  {
    id: "camo-gloves-snow-swedteam",
    category: "camo",
    brand: "Swedteam",
    name: "Hansker Snow",
    priceNok: 449,
    note: "Varme snøhansker — mindre bevegelse = mindre spook.",
    camo: {
      birdSpotSnow: 0.3,
      birdSpotNoSnow: 0.65,
      bestTerrains: ["snow"],
      slot: "gloves",
      terrainSpeed: 5,
      stamina: 6,
    },
  },
  {
    id: "camo-gloves-forest-swedteam",
    category: "camo",
    brand: "Swedteam",
    name: "Hansker Forest",
    priceNok: 449,
    note: "Skoghansker — grep og kamuflasje.",
    camo: {
      birdSpotSnow: 0.68,
      birdSpotNoSnow: 0.3,
      bestTerrains: ["pine_forest", "autumn_forest"],
      slot: "gloves",
      terrainSpeed: 5,
      stamina: 6,
    },
  },
  {
    id: "camo-boots-crispi-titan-evo",
    category: "camo",
    brand: "Crispi",
    name: "Titan Evo",
    priceNok: 5000,
    note: "Premium fjellstøvel. Topp fart/stamina i terreng.",
    camo: {
      birdSpotSnow: 0.45,
      birdSpotNoSnow: 0.4,
      bestTerrains: ["open_mountain", "snow_broken", "general"],
      slot: "boots",
      terrainSpeed: 10,
      stamina: 10,
    },
  },
  {
    id: "camo-boots-lowa",
    category: "camo",
    brand: "Lowa",
    name: "Hunter GTX / fjellstøvel",
    priceNok: 3490,
    note: "Solid tysk jakt-/fjellstøvel.",
    camo: {
      birdSpotSnow: 0.48,
      birdSpotNoSnow: 0.42,
      bestTerrains: ["pine_forest", "open_mountain", "general"],
      slot: "boots",
      terrainSpeed: 8,
      stamina: 8,
    },
  },
  {
    id: "camo-boots-scarpa",
    category: "camo",
    brand: "Scarpa",
    name: "SL Active / jaktstøvel",
    priceNok: 3290,
    note: "Italiensk fjellstøvel — god balanse.",
    camo: {
      birdSpotSnow: 0.5,
      birdSpotNoSnow: 0.43,
      bestTerrains: ["open_mountain", "general"],
      slot: "boots",
      terrainSpeed: 8,
      stamina: 7,
    },
  },
  {
    id: "camo-boots-haix",
    category: "camo",
    brand: "Haix",
    name: "Black Eagle / jaktstøvel",
    priceNok: 2790,
    note: "Robust tjeneste-/jaktstøvel. Litt tyngre.",
    camo: {
      birdSpotSnow: 0.52,
      birdSpotNoSnow: 0.45,
      bestTerrains: ["general", "pine_forest"],
      slot: "boots",
      terrainSpeed: 7,
      stamina: 7,
    },
  },
  {
    id: "camo-ski-boots-budget",
    category: "camo",
    brand: "Budget",
    name: "Skistøvler 1 (plast/NNN-ish)",
    priceNok: 1490,
    note: "Må ha skistøvler for å gå på ski. Budget — verkende tær.",
    camo: {
      birdSpotSnow: 0.55,
      birdSpotNoSnow: 0.55,
      bestTerrains: ["snow"],
      slot: "ski_boots",
      terrainSpeed: 4,
      stamina: 4,
    },
  },
  {
    id: "camo-ski-boots-mid",
    category: "camo",
    brand: "Åsnes / Rottefella",
    name: "Skistøvler 2 (fjell)",
    priceNok: 3490,
    note: "Ordentlige fjellskistøvler — kreves med ski i kit.",
    camo: {
      birdSpotSnow: 0.5,
      birdSpotNoSnow: 0.52,
      bestTerrains: ["snow", "snow_broken"],
      slot: "ski_boots",
      terrainSpeed: 7,
      stamina: 7,
    },
  },
  {
    id: "camo-ski-boots-pro",
    category: "camo",
    brand: "Crispi / Scarpa",
    name: "Skistøvler 3 (pro)",
    priceNok: 5990,
    note: "Premium skistøvel. Best fart/stamina på ski.",
    camo: {
      birdSpotSnow: 0.48,
      birdSpotNoSnow: 0.5,
      bestTerrains: ["snow", "open_mountain"],
      slot: "ski_boots",
      terrainSpeed: 9,
      stamina: 9,
    },
  },
];

function finalizeCatalog(draft: CatalogDraft[]): ShopItem[] {
  return draft.map((item) => {
    const weightGrams = resolveWeightGrams(
      item.id,
      item.category,
      item.weightGrams,
    );
    if (item.category === "rifle") {
      return {
        ...item,
        weightGrams,
        // Source of truth: RIFLE_AVERAGE_BEST_MOA in src/lib/rifle/spec.ts
        rifle: {
          averageBestAccuracyMoa: rifleAverageBestMoa(item.id),
        },
      };
    }
    return { ...item, weightGrams };
  }) as ShopItem[];
}

export const SHOP_CATALOG: ShopItem[] = finalizeCatalog(CATALOG_DRAFT);

/** Full catalog including unobtainable items (for loadouts / gifts). */
export function getShopItem(id: string): ShopItem | undefined {
  return SHOP_CATALOG.find((item) => item.id === id);
}

export function isPurchasableInShop(item: ShopItem): boolean {
  if (item.priceNok <= 0) return false;
  if (item.soldOut) return false;
  if (isCamoItem(item) && item.camo.availableInShop === false) return false;
  // CB Customs home loads — order at the workshop, not XXL.
  if (item.brand === "CB Customs") return false;
  return true;
}

function compareAmmo(a: ShopItem, b: ShopItem): number {
  if (!isAmmoItem(a) || !isAmmoItem(b)) return 0;
  const cal =
    caliberSortIndex(a.ammo.caliber) - caliberSortIndex(b.ammo.caliber);
  if (cal !== 0) return cal;
  const type =
    projectileTypeSortIndex(a.ammo.projectileType) -
    projectileTypeSortIndex(b.ammo.projectileType);
  if (type !== 0) return type;
  return a.brand.localeCompare(b.brand) || a.name.localeCompare(b.name);
}

function compareCamo(a: ShopItem, b: ShopItem): number {
  if (!isCamoItem(a) || !isCamoItem(b)) return 0;
  // Best seasonal score first (lower = better), then the other season.
  const aBest = Math.min(a.camo.birdSpotSnow, a.camo.birdSpotNoSnow);
  const bBest = Math.min(b.camo.birdSpotSnow, b.camo.birdSpotNoSnow);
  if (aBest !== bBest) return aBest - bBest;
  return (
    a.camo.birdSpotSnow +
    a.camo.birdSpotNoSnow -
    (b.camo.birdSpotSnow + b.camo.birdSpotNoSnow)
  );
}

export function getCatalogByCategory(category: ShopItem["category"]): ShopItem[] {
  const items = SHOP_CATALOG.filter((item) => {
    if (item.category !== category) return false;
    if (isPurchasableInShop(item)) return true;
    // Sold-out gear stays visible (greyed) — window shopping / aspiration.
    if (item.soldOut) return true;
    // Unobtainable camo stays visible in the list (never for sale).
    if (
      category === "camo" &&
      isCamoItem(item) &&
      item.camo.availableInShop === false
    ) {
      return true;
    }
    return false;
  });
  if (category === "ammo") {
    return [...items].sort(compareAmmo);
  }
  if (category === "camo") {
    return [...items].sort(compareCamo);
  }
  return items;
}
